import { BUSINESS_MODULES } from '../application/application.mjs';
import { createOperationalApplication } from '../application/operational.mjs';
import { formatMoney, formatStatus } from '../application/formatting.mjs';

const root = document.querySelector('#app');
let app;
const state = { busy: false, notice: null, error: '', lastSale: null, reportQuery: {}, searchResults: null, saleLines: [{ productId: '', quantity: 1, unitPriceMinor: 0 }] };
const route = () => BUSINESS_MODULES.includes(location.hash.slice(1)) ? location.hash.slice(1) : 'dashboard';
const escape = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
const money = (value, currency) => formatMoney(Number.isSafeInteger(Number(value)) ? Number(value) : 0, currency);
const date = value => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const minor = value => Math.round(Number(value || 0) * 100);
const option = (value, label) => `<option value="${escape(value)}">${escape(label)}</option>`;
const empty = message => `<div class="empty">${escape(message)}</div>`;
const status = value => `<span class="pill ${escape(value || '')}">${escape(formatStatus(value || 'unknown'))}</span>`;
const table = (headers, rows, label) => rows.length ? `<div class="table-wrap"><table><caption class="sr-only">${escape(label)}</caption><thead><tr>${headers.map(x => `<th>${escape(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>` : empty(`No ${label.toLowerCase()} yet.`);
const panel = (title, content) => `<section class="panel"><div class="section-head"><h2>${escape(title)}</h2></div>${content}</section>`;
const field = (label, name, type = 'text', extra = '') => `<label><span>${escape(label)}</span><input name="${escape(name)}" type="${type}" ${extra}></label>`;
const notify = () => `${state.notice?.route === route() ? `<div class="notice" role="status">${escape(state.notice.text)}</div>` : ''}${state.error ? `<div class="error" role="alert">${escape(state.error)}</div>` : ''}`;
const chronology = (items, timestamp, renderItems, emptyMessage) => {
  const sorted = [...items].filter(item => timestamp(item)).sort((a, b) => new Date(timestamp(b)) - new Date(timestamp(a))), years = new Map();
  for (const item of sorted) { const value = new Date(timestamp(item)), year = new Intl.DateTimeFormat(undefined, { year: 'numeric' }).format(value), month = new Intl.DateTimeFormat(undefined, { month: 'long' }).format(value), day = new Intl.DateTimeFormat(undefined, { weekday: 'long', day: 'numeric' }).format(value); if (!years.has(year)) years.set(year, new Map()); if (!years.get(year).has(month)) years.get(year).set(month, new Map()); if (!years.get(year).get(month).has(day)) years.get(year).get(month).set(day, []); years.get(year).get(month).get(day).push(item); }
  if (!sorted.length) return empty(emptyMessage);
  return `<div class="chronology">${[...years].map(([year, months]) => `<section class="chronology-year"><h3>${escape(year)}</h3>${[...months].map(([month, days]) => `<section class="chronology-month"><h4>${escape(month)}</h4>${[...days].map(([day, entries]) => `<section class="chronology-day"><h5>${escape(day)}</h5>${renderItems(entries)}</section>`).join('')}</section>`).join('')}</section>`).join('')}</div>`;
};
const chronologicalTable = (items, timestamp, headers, row, label) => chronology(items, timestamp, entries => table(headers, entries.map(row), label), `No ${label.toLowerCase()} yet.`);

function shell(ctx, health, active) {
  return `<div class="shell"><aside class="nav" id="nav"><div class="brand">Free Ofis <span class="dev">V4 DEVELOPMENT — NO CUTOVER</span></div><p class="muted">Business workspace</p><nav aria-label="Business modules">${BUSINESS_MODULES.map(name => `<a href="#${name}" data-route="${name}" aria-current="${active === name ? 'page' : 'false'}">${escape(formatStatus(name))}</a>`).join('')}</nav></aside><main class="main"><header class="top"><div><button class="menu" id="menu" aria-label="Toggle navigation" aria-controls="nav">☰</button><h1>${escape(formatStatus(active))}</h1><p class="muted">${escape(ctx.workspace)} · ${escape(ctx.baseCurrency)}</p></div><span class="health ${health.status === 'healthy' ? '' : 'warning'}">Health: ${escape(health.status)}</span></header><form id="search-form" class="global-search" role="search"><input name="query" aria-label="Search Free Ofis" placeholder="Search customers, products, sales, purchases…"><select name="category" aria-label="Search category"><option value="all">All</option>${['customers','suppliers','products','sales','purchases','payments','finance','activity'].map(x=>option(x,formatStatus(x))).join('')}</select><button>Search</button></form>${state.searchResults ? `<section class="search-results">${state.searchResults.length ? state.searchResults.map(item=>`<article><strong>${escape(item.title)}</strong><span>${escape(formatStatus(item.category))} · ${escape(item.summary)}</span></article>`).join('') : empty('No matching records.')}</section>` : ''}<div id="messages">${notify()}</div><section id="view" aria-live="polite"></section></main></div>`;
}

function dashboardView(data, currency) {
  const cards = [['Sales today', data.salesTodayMinor], ['Units sold today', data.grossUnitsToday, true], ['Cash at Hand', data.cashAtHandMinor], ['Customer receivables', data.customerReceivablesMinor], ['Supplier payables', data.supplierPayablesMinor], ['Current P&L', data.pnl.netProfitMinor]];
  return `<div class="cards">${cards.map(([label, value, count]) => `<article class="card"><div class="muted">${label}</div><div class="metric">${count ? value : money(value, currency)}</div></article>`).join('')}<article class="card ${data.warnings.length ? 'warning' : ''}"><div class="muted">Finance warnings</div><div class="metric">${data.warnings.length}</div></article></div>`;
}

function salesView(data, currency) {
  const products = data.products.filter(product => product.status === 'active');
  const total = state.saleLines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitPriceMinor || 0), 0);
  const lines = state.saleLines.map((line, index) => `<div class="line-item" data-line="${index}"><label><span>Product</span><select data-line-field="productId"><option value="">Select product</option>${products.map(product => `<option value="${escape(product.id)}" data-price="${product.defaultSellingPriceMinor ?? 0}">${escape(`${product.name} · ${data.stocks[product.id] || 0} available`)}</option>`).join('')}</select></label>${field('Quantity', 'quantity', 'number', `min="1" step="1" value="${line.quantity}" data-line-field="quantity"`)}${field('Unit price', 'unitPrice', 'number', `min="0" step="0.01" value="${(line.unitPriceMinor / 100).toFixed(2)}" data-line-field="unitPrice"`)}<strong>${money(Number(line.quantity) * Number(line.unitPriceMinor), currency)}</strong><button type="button" class="quiet danger" data-action="remove-line" data-index="${index}" ${state.saleLines.length === 1 ? 'disabled' : ''}>Remove</button></div>`).join('');
  const history = chronologicalTable(data.orders, order => order.transactionAt, ['Sale', 'Time', 'Customer', 'Total', 'Payment'], order => { const invoice = data.invoices.find(item => item.salesOrderId === order.id); return `<tr><td>${escape(order.orderNumber)}</td><td>${date(order.transactionAt)}</td><td>${escape(order.customerNameSnapshot || 'Walk-in')}</td><td>${money(order.expectedAmountMinor, currency)}</td><td>${status(invoice?.paymentStatus || order.status)}</td></tr>`; }, 'Sales');
  const completed = state.lastSale ? panel('Sale completed', `<div class="completed"><div><strong>${escape(state.lastSale.primaryEntity.orderNumber)}</strong><p>${escape(state.lastSale.primaryEntity.customerNameSnapshot || 'Walk-in')} · ${money(state.lastSale.primaryEntity.expectedAmountMinor, currency)}</p></div><div><button type="button" data-action="view-receipt">View Receipt</button><button type="button" class="secondary" data-action="print-receipt">Print</button><button type="button" class="secondary" data-action="new-sale">New Sale</button></div></div><div id="receipt-preview" hidden></div>`) : '';
  return `${completed}${panel('New sale', `<form id="sale-form"><div class="form-grid"><label><span>Customer</span><select name="customerId"><option value="">Walk-in (full payment only)</option>${data.customers.map(customer => option(customer.id, customer.name)).join('')}</select></label><label><span>Payment method</span><select name="method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option></select></label>${field('Amount paid', 'amountPaid', 'number', `min="0" step="0.01" value="${(total / 100).toFixed(2)}" required`)}<label data-credit-control hidden><span>Credit due</span><select name="duePreset" disabled><option value="">No agreed due date</option><option value="0">Today</option><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option><option value="custom">Custom</option></select></label><label data-credit-control hidden><span>Custom due date</span><input name="customDueAt" type="date" disabled></label></div><div class="line-list">${lines}</div><div class="sale-total"><button type="button" class="secondary" data-action="add-line">Add line</button><strong>Total: ${money(total, currency)}</strong></div><button ${state.busy || !products.length ? 'disabled' : ''}>Complete sale</button>${!products.length ? '<p class="hint">Add and stock a product before making a sale.</p>' : ''}</form>`)}${panel('Sales history', history)}`;
}

function customersView(data, currency) {
  const outstanding = data.rows.flatMap(row => row.invoices.filter(item => item.balance.outstandingMinor > 0).map(item => ({ customer: row.customer, ...item })));
  const transaction = entry => { if (entry.type === 'payment') return `<div class="transaction-story"><h3>Payment applied to invoice</h3><p>${date(entry.at)} · ${money(entry.allocation.amountMinor, currency)} · ${escape(formatStatus(entry.allocation.payment?.method || 'unknown'))} · ${escape(entry.invoice.invoiceNumber)}</p></div>`; const item = entry.item, paid = item.invoice.totalMinor - item.balance.outstandingMinor, due = !item.invoice.dueAt ? '' : item.balance.outstandingMinor === 0 ? 'Paid' : new Date(item.invoice.dueAt) < new Date() ? 'Overdue' : new Date(item.invoice.dueAt).toDateString() === new Date().toDateString() ? 'Due Today' : 'Not Due'; return `<div class="transaction-story"><h3>${escape(item.order?.orderNumber || item.invoice.invoiceNumber)} ${status(item.invoice.paymentStatus)}</h3><p>${date(item.invoice.transactionAt)} · Total ${money(item.invoice.totalMinor, currency)} · Paid ${money(paid, currency)} · Balance ${money(item.balance.outstandingMinor, currency)} ${due ? `· ${status(due.toLowerCase().replaceAll(' ', '_'))}` : ''}</p><ul>${item.lines.map(line => `<li>${escape(line.productNameSnapshot)} × ${line.quantity} @ ${money(line.unitPriceMinor, currency)}</li>`).join('')}</ul></div>`; };
  const rows = data.rows.map(row => { const history = row.invoices.flatMap(item => [{ type: 'invoice', at: item.invoice.transactionAt, item }, ...item.payments.filter(allocation => allocation.payment?.transactionAt).map(allocation => ({ type: 'payment', at: allocation.payment.transactionAt, allocation, invoice: item.invoice }))]); return `<article class="ledger-card"><header><div><strong>${escape(row.customer.name)}</strong><small>${escape(row.customer.phone || row.customer.email || '')}</small></div><div><span>Outstanding</span><strong>${money(row.outstandingMinor, currency)}</strong></div></header><div class="ledger-totals"><span>Total purchases ${money(row.totalPurchasesMinor, currency)}</span><span>Total paid ${money(row.totalPaidMinor, currency)}</span><span>Last activity ${date(row.lastActivityAt)}</span></div><details><summary>View transactions and statement</summary>${chronology(history, item => item.at, items => items.map(transaction).join(''), 'No customer transactions yet.')}</details></article>`; }).join('');
  return `${panel('Add customer', `<form id="customer-form" class="form-grid">${field('Name', 'name', 'text', 'required')}${field('Phone', 'phone', 'tel')}${field('Email', 'email', 'email')}<button ${state.busy ? 'disabled' : ''}>Add customer</button></form>`)}${outstanding.length ? panel('Record customer payment', `<form id="customer-payment-form" class="form-grid"><label><span>Outstanding invoice</span><select name="invoice" required><option value="">Select invoice</option>${outstanding.map(item=>option(`${item.customer.id}|${item.invoice.id}|${item.balance.outstandingMinor}`,`${item.customer.name} · ${item.invoice.invoiceNumber} · ${money(item.balance.outstandingMinor,currency)}`)).join('')}</select></label>${field('Amount received','amount','number','min="0.01" step="0.01" required')}<label><span>Method</span><select name="method"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option></select></label><button>Record payment</button></form>`) : ''}${panel('Customer relationships', rows || empty('No customers yet.'))}`;
}

function inventoryView(data, currency) {
  const rows = data.rows.map(({ product, stock, cost }) => `<tr><td><strong>${escape(product.name)}</strong><br><small>${escape(product.description || '')}</small></td><td>${stock.quantity}</td><td>${product.defaultSellingPriceMinor == null ? '—' : money(product.defaultSellingPriceMinor, currency)}</td><td>${cost.costStatus === 'known' ? money(cost.unitCostMinor, currency) : '<span class="muted">Unknown</span>'}</td><td>${status(stock.quantity < 0 ? 'negative' : stock.quantity === 0 ? 'out_of_stock' : 'available')}</td></tr>`);
  const movements = chronologicalTable(data.movements.slice(0, 30), item => item.transactionAt || item.createdAt, ['Time', 'Product', 'Movement', 'Quantity'], item => `<tr><td>${date(item.transactionAt || item.createdAt)}</td><td>${escape(data.rows.find(row => row.product.id === item.productId)?.product.name || item.productId)}</td><td>${escape(formatStatus(item.movementType))}</td><td>${item.signedQuantity}</td></tr>`, 'Stock movements');
  return `${panel('Add product', `<form id="product-form" class="form-grid">${field('Product name', 'name', 'text', 'required')}${field('Selling price', 'sellingPrice', 'number', 'min="0" step="0.01"')}${field('Description', 'description')}<button ${state.busy ? 'disabled' : ''}>Add product</button></form>`)}${panel('Adjust stock', `<form id="stock-form" class="form-grid"><label><span>Product</span><select name="productId" required><option value="">Select product</option>${data.rows.map(row => option(row.product.id, row.product.name)).join('')}</select></label>${field('Quantity change', 'quantity', 'number', 'step="1" required placeholder="Use -2 to reduce"')}<button ${state.busy ? 'disabled' : ''}>Record adjustment</button></form><p class="hint">Stock changes are recorded as movements; balances are never overwritten.</p>`)}${panel('Products', table(['Product', 'Available', 'Selling price', 'Known average cost', 'Status'], rows, 'Products'))}${panel('Recent stock movements', movements)}`;
}

function purchasesView(data, currency) {
  const rows = chronology(data.receipts,row=>row.receipt.transactionAt,items=>items.map(row => `<article class="ledger-card"><header><div><strong>${escape(data.suppliers.find(s=>s.id===row.receipt.supplierId)?.name||'Supplier')}</strong><small>${date(row.receipt.transactionAt)}</small></div><div><strong>${row.totalMinor===null?'Unknown value':money(row.totalMinor,currency)}</strong>${status(row.settlementStatus)}</div></header><ul>${row.lines.map(line=>`<li>${escape(data.products.find(p=>p.id===line.productId)?.name||'Product')} × ${line.quantity} @ ${line.unitCostMinor===null?'Unknown':money(line.unitCostMinor,currency)}</li>`).join('')}</ul><p>Paid ${money(row.amountPaidMinor,currency)} · Payable ${row.outstandingMinor===null?'Not recorded':money(row.outstandingMinor,currency)}</p><details><summary>Technical details</summary><code>${escape(row.receipt.id)}</code></details></article>`).join(''),'No stock receipts yet.');
  return `${panel('Receive a purchase', `<form id="purchase-form" class="form-grid"><label><span>Supplier</span><select name="supplierId" required><option value="">Select supplier</option>${data.suppliers.map(supplier => option(supplier.id, supplier.name)).join('')}</select></label><label><span>Product</span><select name="productId" required><option value="">Select product</option>${data.products.map(product => option(product.id, product.name)).join('')}</select></label>${field('Quantity', 'quantity', 'number', 'min="1" step="1" required')}${field('Unit acquisition cost', 'unitCost', 'number', 'min="0" step="0.01" required')}<label><span>Settlement</span><select name="settlement"><option value="paid">Paid in full</option><option value="part">Part paid</option><option value="credit">Credit</option></select></label>${field('Amount paid', 'amountPaid', 'number', 'min="0" step="0.01" value="0"')}<label><span>Payment method</span><select name="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option></select></label><button ${state.busy || !data.suppliers.length || !data.products.length ? 'disabled' : ''}>Receive and record settlement</button></form><p class="hint">The receipt, supplier invoice, payment allocation and accounting postings remain separate immutable records.</p>`)}${panel('Purchase history', rows)}`;
}

function suppliersView(data, currency) {
  const unpaid=data.rows.flatMap(row=>row.unpaidInvoices.map(invoice=>({supplier:row.supplier,invoice}))),rows=data.rows.map(row=>{const history=[...row.purchases.map(purchase=>({type:'purchase',at:purchase.receipt.transactionAt,value:purchase})),...row.payments.map(payment=>({type:'payment',at:payment.transactionAt,value:payment}))];return `<article class="ledger-card"><header><div><strong>${escape(row.supplier.name)}</strong><small>${escape(row.supplier.phone||row.supplier.email||'')}</small></div><strong>Owed ${money(row.outstandingMinor,currency)}</strong></header><div class="ledger-totals"><span>${row.purchases.length} purchases</span><span>Total ${money(row.totalPurchasesMinor,currency)}</span><span>Paid ${money(row.totalPaidMinor,currency)}</span><span>Last purchase ${date(row.lastPurchaseAt)}</span></div><details><summary>View purchase and payment history</summary>${chronology(history,item=>item.at,items=>items.map(item=>item.type==='payment'?`<div class="transaction-story"><strong>Supplier payment recorded</strong><p>${date(item.at)} · ${money(item.value.amountMinor,currency)} · ${escape(formatStatus(item.value.method||'unknown'))}</p></div>`:`<div class="transaction-story"><strong>Purchase received</strong><p>${date(item.at)} · ${item.value.totalMinor===null?'Unknown value':money(item.value.totalMinor,currency)} · Paid ${money(item.value.amountPaidMinor,currency)} · Owed ${item.value.outstandingMinor===null?'Not recorded':money(item.value.outstandingMinor,currency)}</p></div>`).join(''),'No supplier transactions yet.')}</details></article>`}).join('');
  return `${panel('Add supplier', `<form id="supplier-form" class="form-grid">${field('Supplier name', 'name', 'text', 'required')}${field('Phone', 'phone', 'tel')}${field('Email', 'email', 'email')}<button ${state.busy ? 'disabled' : ''}>Add supplier</button></form>`)}${unpaid.length?panel('Pay supplier',`<form id="supplier-payment-form" class="form-grid"><label><span>Outstanding invoice</span><select name="invoice" required><option value="">Select invoice</option>${unpaid.map(item=>option(`${item.supplier.id}|${item.invoice.id}|${item.invoice.outstandingMinor}`,`${item.supplier.name} · ${money(item.invoice.outstandingMinor,currency)}`)).join('')}</select></label>${field('Amount paid','amount','number','min="0.01" step="0.01" required')}<label><span>Method</span><select name="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option></select></label><button>Record supplier payment</button></form>`):''}${panel('Supplier relationships',rows||empty('No suppliers yet.'))}`;
}

function financeView(data, currency) {
  const p = data.pnl, b = data.balanceSheet;
  const expenses = chronologicalTable(data.expenses,expense=>expense.expenseAt,['Time', 'Description', 'Category', 'Amount'],expense => `<tr><td>${date(expense.expenseAt)}</td><td>${escape(expense.description)}</td><td>${escape(expense.category || 'Uncategorised')}</td><td>${money(expense.amountMinor, currency)}</td></tr>`,'Expenses');
  const expenseAccounts = data.accounts.filter(account => account.accountType === 'expense' && account.postingAllowed);
  return `<div class="cards">${[['Revenue', p.revenueMinor], ['Gross profit', p.grossProfitMinor], ['Operating expenses', p.operatingExpensesMinor], ['Net profit', p.netProfitMinor], ['Assets', b.assetsMinor], ['Liabilities', b.liabilitiesMinor]].map(([label, value]) => `<article class="card"><div class="muted">${label}</div><div class="metric">${money(value, currency)}</div></article>`).join('')}</div>${panel('Record expense', `<form id="expense-form" class="form-grid"><label><span>Expense account</span><select name="expenseAccountId" required><option value="">Select account</option>${expenseAccounts.map(account => option(account.id, account.name)).join('')}</select></label><label><span>Paid from</span><select name="financialAccountId" required>${data.financialAccounts.map(account => option(account.id, account.displayName)).join('')}</select></label>${field('Amount', 'amount', 'number', 'min="0.01" step="0.01" required')}${field('Description', 'description', 'text', 'required')}<button ${state.busy || !expenseAccounts.length ? 'disabled' : ''}>Record expense</button></form>${!expenseAccounts.length ? '<p class="hint">No custom posting expense account is available yet. Account setup is a genuine remaining Settings capability.</p>' : ''}`)}${panel('Expenses', expenses)}${panel('Trial balance', `<p>${data.trialBalance.balanced ? 'Balanced' : 'Attention required'} · Debits ${money(data.trialBalance.totalDebitsMinor, currency)} · Credits ${money(data.trialBalance.totalCreditsMinor, currency)}</p>${data.failures.filter(x => x.resolutionStatus === 'unresolved').length ? '<p class="warning">Some finance postings need review.</p>' : ''}`)}`;
}

function reportsView(data, currency) {
  const r = data.salesReport;
  return `${panel('Date filter', `<div class="quick-ranges">${['today','yesterday','week','month','custom'].map(range=>`<button type="button" class="secondary" data-range="${range}">${escape(formatStatus(range))}</button>`).join('')}</div><form id="report-form" class="form-grid">${field('From', 'from', 'date',`value="${escape(state.reportQuery.from?.slice(0,10)||'')}"`)}${field('To', 'to', 'date',`value="${escape(state.reportQuery.to?.slice(0,10)||'')}"`)}<button>Apply</button></form>`)}<div class="cards">${[['Sales', r.revenueMinor], ['Units sold', r.netUnitsSold, true], ['Purchases', data.purchaseTotalMinor], ['Expenses', data.pnl.operatingExpensesMinor], ['Cash collected', data.dashboard.cashAtHandMinor], ['Receivables', data.dashboard.customerReceivablesMinor]].map(([label, value, count]) => `<a class="card card-link" href="#${label==='Purchases'?'purchases':label==='Expenses'?'finance':label==='Receivables'?'customers':'sales'}"><div class="muted">${label}</div><div class="metric">${count ? value : money(value, currency)}</div></a>`).join('')}</div>${panel('Inventory remaining', table(['Product', 'Quantity', 'Average cost', 'Reliable stock value'], data.inventoryRows.map(row => `<tr><td>${escape(row.product.name)}</td><td>${row.stock.quantity}</td><td>${row.cost.costStatus==='known'?money(row.cost.unitCostMinor,currency):'Unknown'}</td><td>${row.cost.costStatus==='known'?money(row.stock.quantity*row.cost.unitCostMinor,currency):'Unknown valuation'}</td></tr>`), 'Inventory report'))}`;
}

function activityView(events) {
  const language={"sale.fulfilled":'Sale completed',"sales_order.created":'Sale created',"sales_order.confirmed":'Sale confirmed',"customer_invoice.issued":'Customer invoice issued',"customer_payment.recorded":'Payment received',"customer_payment.allocated":'Payment applied to invoice',"supplier_payment.recorded":'Supplier payment recorded',"supplier_payment.allocated":'Supplier payment applied',"journal.posted":'Accounting entry posted',"goods.received":'Stock received',"product.created":'Product added',"customer.created":'Customer added',"supplier.created":'Supplier added',"expense.recorded":'Expense recorded'},system=event=>/bootstrap|^identity\.|^legacy\./i.test(event.eventType),renderEvents=items=>items.map(event=>`<article class="event"><div><strong>${escape(language[event.eventType]||formatStatus(event.eventType.replaceAll('.','_')))}</strong><div class="muted">${new Intl.DateTimeFormat(undefined,{timeStyle:'short'}).format(new Date(event.eventAt))}</div></div><div>${escape(formatStatus(event.entityType))}</div><details><summary>Technical details</summary><code>${escape(event.entityId)}</code><br><small>Event type: ${escape(event.eventType)}</small>${event.actorId?`<br><small>Actor: ${escape(event.actorId)}</small>`:''}</details></article>`).join(''),businessEvents=events.filter(event=>!system(event)),systemEvents=events.filter(system);
  return panel('Business activity', `${chronology(businessEvents,event=>event.eventAt,renderEvents,'No business activity yet.')}${systemEvents.length?`<details class="system-activity"><summary>System and technical activity (${systemEvents.length})</summary>${chronology(systemEvents,event=>event.eventAt,renderEvents,'No system activity.')}</details>`:''}`);
}

function settingsView(data) {
  const current = data.context;
  return `${panel('Current workspace', `<dl class="details"><div><dt>Workspace</dt><dd>${escape(formatStatus(current.workspace))}</dd></div><div><dt>Business</dt><dd>${escape(data.contexts.businesses.find(x => x.id === current.businessId)?.name || current.businessId)}</dd></div><div><dt>Operating unit</dt><dd>${escape(data.contexts.operatingUnits.find(x => x.id === current.operatingUnitId)?.name || current.operatingUnitId)}</dd></div><div><dt>Currency</dt><dd>${escape(current.baseCurrency)}</dd></div></dl>`)}${panel('Available workspaces', `<div class="workspace-list">${data.workspaces.map(workspace => `<div><strong>${escape(workspace.label)}</strong>${workspace.enabled ? status('available') : status('coming_later')}</div>`).join('')}</div><p class="hint">Only settings persisted and enforced by the current architecture are shown. Business editing and account configuration are not yet exposed.</p>`)}`;
}

function migrationView() {
  return panel('Verified migration', `<p class="warning"><strong>NO PRODUCTION CUTOVER HAS OCCURRED</strong></p><ol class="steps"><li>Backup</li><li>Analyze</li><li>Resolve</li><li>Rehearse</li><li>Reconcile</li><li>Ready for Cutover</li></ol><p>This development screen never reads production V3 storage automatically. Migration requires a separately authorized, explicit source snapshot and controlled procedure.</p><button disabled>Cut Over</button>`);
}

async function render() {
  const active = route(), ctx = app.getContext(), health = await app.health();
  root.innerHTML = shell(ctx, health, active);
  document.querySelector('#menu').onclick = () => document.querySelector('#nav').classList.toggle('open');
  document.querySelectorAll('[data-route]').forEach(link => link.onclick = () => document.querySelector('#nav').classList.remove('open'));
  const view = document.querySelector('#view');
  if (active === 'dashboard') view.innerHTML = dashboardView(await app.dashboard(), ctx.baseCurrency);
  else if (active === 'activity') view.innerHTML = activityView(await app.activity());
  else if (active === 'migration') view.innerHTML = migrationView();
  else { const data = ['customers','purchases','suppliers','reports'].includes(active) ? await app.operationalData(active,active==='reports'?state.reportQuery:{}) : await app.screenData(active); view.innerHTML = ({ sales: salesView, customers: customersView, inventory: inventoryView, purchases: purchasesView, suppliers: suppliersView, finance: financeView, reports: reportsView, settings: settingsView })[active](data, ctx.baseCurrency); }
  bind();
}

async function submit(work, success) {
  state.busy = true; state.error = ''; state.notice = '';
  try { const result = await work(); if (result?.ok === false) throw new Error(result.message); state.notice = {route:route(),text:typeof success==='function'?success(result):success}; return result; }
  catch (error) { state.error = error.message || String(error); }
  finally { state.busy = false; await render(); }
}

function bind() {
  document.querySelectorAll('[data-line-field]').forEach(control => { const line = state.saleLines[Number(control.closest('[data-line]').dataset.line)]; control.value = control.dataset.lineField === 'unitPrice' ? (line.unitPriceMinor / 100).toFixed(2) : line[control.dataset.lineField]; control.onchange = () => { line[control.dataset.lineField] = control.dataset.lineField === 'unitPrice' ? minor(control.value) : control.dataset.lineField === 'quantity' ? Number(control.value) : control.value; if(control.dataset.lineField === 'productId' && !line.unitPriceMinor)line.unitPriceMinor=Number(control.selectedOptions[0]?.dataset.price||0); render(); }; });
  document.querySelectorAll('[data-action]').forEach(button => button.onclick = () => { if(button.dataset.action==='view-receipt'){const preview=document.querySelector('#receipt-preview');preview.hidden=!preview.hidden;preview.innerHTML=`<pre>${escape(JSON.stringify(state.lastSale.generatedDocuments?.[0]||{},null,2))}</pre>`;return}if(button.dataset.action==='print-receipt'){window.print();return}if(button.dataset.action==='new-sale'){state.lastSale=null;state.saleLines=[{productId:'',quantity:1,unitPriceMinor:0}];render();return}if (button.dataset.action === 'add-line') state.saleLines.push({ productId: '', quantity: 1, unitPriceMinor: 0 }); else state.saleLines.splice(Number(button.dataset.index), 1); render(); });
  const on = (id, handler) => { const form = document.querySelector(id); if (form) form.onsubmit = event => { event.preventDefault(); handler(new FormData(form)); }; };
  const saleForm=document.querySelector('#sale-form');if(saleForm){const customer=saleForm.elements.customerId,creditControls=[...saleForm.querySelectorAll('[data-credit-control]')],syncCredit=()=>{const known=Boolean(customer.value);for(const label of creditControls){label.hidden=!known;for(const control of label.querySelectorAll('input,select')){control.disabled=!known;if(!known)control.value=''}}};customer.onchange=syncCredit;syncCredit()}
  const purchaseForm=document.querySelector('#purchase-form');if(purchaseForm){const quantity=purchaseForm.elements.quantity,cost=purchaseForm.elements.unitCost,settlement=purchaseForm.elements.settlement,paid=purchaseForm.elements.amountPaid,syncSettlement=()=>{const total=Number(quantity.value||0)*Number(cost.value||0);if(settlement.value==='paid'){paid.value=total.toFixed(2);paid.readOnly=true}else if(settlement.value==='credit'){paid.value='0.00';paid.readOnly=true}else paid.readOnly=false};for(const control of[quantity,cost,settlement])control.addEventListener('input',syncSettlement);syncSettlement()}
  on('#customer-form', data => submit(() => app.createCustomer({ name: data.get('name'), phone: data.get('phone') || null, email: data.get('email') || null }), 'Customer added.'));
  on('#supplier-form', data => submit(() => app.createSupplier({ name: data.get('name'), phone: data.get('phone') || null, email: data.get('email') || null }), 'Supplier added.'));
  on('#product-form', data => submit(() => app.createProduct({ name: data.get('name'), description: data.get('description') || null, defaultSellingPriceMinor: data.get('sellingPrice') ? minor(data.get('sellingPrice')) : null, sellingCurrency: app.getContext().baseCurrency }), 'Product added.'));
  on('#stock-form', data => submit(() => app.adjustStock({ productId: data.get('productId'), quantity: Number(data.get('quantity')) }), 'Stock adjustment recorded.'));
  on('#purchase-form', data => {const quantity=Number(data.get('quantity')),unitCostMinor=minor(data.get('unitCost')),total=quantity*unitCostMinor,settlement=data.get('settlement'),amountPaidMinor=settlement==='paid'?total:settlement==='credit'?0:minor(data.get('amountPaid'));submit(() => app.completePurchase({ supplierId: data.get('supplierId'), amountPaidMinor, paymentMethod:data.get('method'), lines: [{ productId: data.get('productId'), quantity, unitCostMinor, currency: app.getContext().baseCurrency, ownershipId: app.getContext().inventoryOwnershipId }] }), result=>`Purchase recorded. Paid ${money(result.primaryEntity.settlement.amountPaidMinor,app.getContext().baseCurrency)}; payable ${money(result.primaryEntity.settlement.outstandingMinor,app.getContext().baseCurrency)}.`)});
  on('#expense-form', data => submit(() => app.recordExpense({ expenseAccountId: data.get('expenseAccountId'), financialAccountId: data.get('financialAccountId'), amountMinor: minor(data.get('amount')), currency: app.getContext().baseCurrency, description: data.get('description') }), 'Expense recorded.'));
  on('#customer-payment-form',data=>{const[customerId,invoiceId,max]=data.get('invoice').split('|'),amountMinor=minor(data.get('amount'));if(amountMinor>Number(max)){state.error='Payment exceeds the selected invoice balance.';render();return}submit(()=>app.recordCustomerPayment({customerId,amountMinor,currency:app.getContext().baseCurrency,allocations:[{invoiceId,amountMinor}],method:data.get('method'),idempotencyKey:`ui-payment-${crypto.randomUUID()}`}), 'Payment received and allocated to the selected invoice.')});
  on('#supplier-payment-form',data=>{const[supplierId,invoiceId,max]=data.get('invoice').split('|'),amountMinor=minor(data.get('amount'));if(amountMinor>Number(max)){state.error='Payment exceeds the selected supplier invoice balance.';render();return}submit(()=>app.recordSupplierPayment({supplierId,invoiceId,amountMinor,method:data.get('method')}),'Supplier payment recorded and allocated.')});
  on('#sale-form', data => { const customerId = data.get('customerId') || null, total = state.saleLines.reduce((n, line) => n + line.quantity * line.unitPriceMinor, 0), paid = minor(data.get('amountPaid')),preset=data.get('duePreset'),dueAt=customerId===null?null:!preset?null:preset==='custom'?(data.get('customDueAt')?`${data.get('customDueAt')}T23:59:59.999Z`:null):new Date(Date.now()+Number(preset)*86400000).toISOString(); submit(() => app.completeSale({ customerId, dueAt, currency: app.getContext().baseCurrency, idempotencyKey: `ui-sale-${crypto.randomUUID()}`, allowCredit: customerId !== null && paid < total, lines: state.saleLines.map((line, index) => ({ ...line, productNameSnapshot: document.querySelector(`[data-line="${index}"] option:checked`)?.textContent?.split(' · ')[0] || 'Product', ownershipId: app.getContext().inventoryOwnershipId })), payment: paid > 0 ? { amountMinor: paid, method: data.get('method') } : undefined }), result=>`Sale ${result.primaryEntity.orderNumber} completed.`).then(result => { if (!state.error&&result){state.lastSale=result;state.saleLines=[{ productId: '', quantity: 1, unitPriceMinor: 0 }];render()} }); });
  on('#report-form', data => {state.reportQuery={from:data.get('from')?`${data.get('from')}T00:00:00.000Z`:'',to:data.get('to')?`${data.get('to')}T23:59:59.999Z`:''};state.notice={route:'reports',text:'Report date filter applied.'};render()});
  on('#search-form',data=>app.searchOperational(data.get('query'),data.get('category')).then(results=>{state.searchResults=results;render()}));
  document.querySelectorAll('[data-range]').forEach(button=>button.onclick=()=>{const now=new Date(),start=new Date(now),end=new Date(now);if(button.dataset.range==='yesterday'){start.setDate(now.getDate()-1);end.setDate(now.getDate()-1)}else if(button.dataset.range==='week')start.setDate(now.getDate()-((now.getDay()+6)%7));else if(button.dataset.range==='month')start.setDate(1);else if(button.dataset.range==='custom'){state.reportQuery={};render();return}start.setHours(0,0,0,0);end.setHours(23,59,59,999);state.reportQuery={from:start.toISOString(),to:end.toISOString()};render()});
}

addEventListener('hashchange', () => {state.error='';state.searchResults=null;render()});
addEventListener('beforeunload', () => app?.close());
try { const requestedDatabase = new URLSearchParams(location.search).get('testDatabase'); app = await createOperationalApplication({ databaseName: requestedDatabase?.startsWith('freeofis_v4_') && requestedDatabase.endsWith('_test') ? requestedDatabase : undefined }); await render(); }
catch (error) { root.innerHTML = `<main class="fatal"><h1>Free Ofis V4 Development</h1><div class="error"><strong>Could not start V4</strong><pre>${escape(error.message)}</pre></div></main>`; }
