import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';
import{createV4Application}from'../v4/application/application.mjs';import{createMigrationService,sha256}from'../v4/migration/migration.mjs';import{V3_STORAGE_KEYS}from'../v4/legacy/legacy-reader.mjs';import{V4_DATABASE_NAME,V4_STORES}from'../v4/persistence/schema.mjs';import{AUTHORIZED_WARNINGS,PRODUCTION_CONFIGURATION,createProductionCutoverController,parseAuthorizedSnapshot}from'../v4/migration/production-cutover-control.mjs';import{MemoryV4Persistence}from'./helpers/memory-v4-persistence.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),html=fs.readFileSync(path.join(root,'v4/migration/production-cutover.html'),'utf8'),ui=fs.readFileSync(path.join(root,'v4/migration/production-cutover-ui.mjs'),'utf8'),controlSource=fs.readFileSync(path.join(root,'v4/migration/production-cutover-control.mjs'),'utf8'),stamp='2026-08-18T22:00:00Z',context={clock:()=>new Date(stamp)},rawValues={[V3_STORAGE_KEYS.dataVersion]:'3',[V3_STORAGE_KEYS.inventory]:'[{"id":"p1","name":"Stock","quantity":2,"price":100}]',[V3_STORAGE_KEYS.customers]:'[]',[V3_STORAGE_KEYS.sales]:'[]',[V3_STORAGE_KEYS.payments]:'[]',[V3_STORAGE_KEYS.expenses]:'[]',[V3_STORAGE_KEYS.business]:'{"name":"Legacy"}'},envelope={rawValues,createdBy:'operator',buildReference:'test',createdAt:stamp},bytes=new TextEncoder().encode(JSON.stringify(envelope)),checksum=(await sha256(new TextDecoder().decode(bytes))).toUpperCase();
async function setup(confirmFinalCutover=()=>true){const persistence=new MemoryV4Persistence(),app=await createV4Application({persistence,context,bootstrap:{businessName:PRODUCTION_CONFIGURATION.businessName,operatingUnitName:PRODUCTION_CONFIGURATION.operatingUnitName,defaultCurrency:'NGN'}}),migration=createMigrationService(persistence,{context,cryptoApi:globalThis.crypto}),controller=createProductionCutoverController({app,migration,databaseName:V4_DATABASE_NAME,clock:context.clock,confirmFinalCutover});await controller.importSnapshot(bytes.buffer,{authorizedChecksum:checksum});return{persistence,app,migration,controller}}
async function throughOpening(confirm){const s=await setup(confirm);await s.controller.verifyTarget();await s.controller.executeMigration();const reconciliation=await s.controller.reconcile();await s.controller.recordZeroOpeningPosition();return{...s,reconciliation}}

assert.match(html,/FRESH V4 START — NO V3 MIGRATION/);assert.match(ui,/createFreshProductionController/);assert.doesNotMatch(ui,/createMigrationService|localStorage|sessionStorage|file:\/\//);assert.doesNotMatch(controlSource,/localStorage|sessionStorage|file:\/\//);
await assert.rejects(parseAuthorizedSnapshot(bytes.buffer,{authorizedChecksum:'0'.repeat(64)}),/SNAPSHOT_FILE_CHECKSUM_MISMATCH/);
{const s=await setup();await s.app.createProduct({name:'Existing production product'});await assert.rejects(s.controller.verifyTarget(),/TARGET_V4_NOT_EMPTY/)}
{const s=await setup(),first=s.controller.state.snapshot,refreshed=createProductionCutoverController({app:s.app,migration:s.migration,databaseName:V4_DATABASE_NAME,clock:context.clock});const second=await refreshed.importSnapshot(bytes.buffer,{authorizedChecksum:checksum});assert.equal(second.id,first.id);assert.equal((await s.persistence.getAll(V4_STORES.migrationSnapshots)).length,1)}
{const s=await setup(),snapshot=s.controller.state.snapshot,refreshed=createProductionCutoverController({app:s.app,migration:s.migration,databaseName:V4_DATABASE_NAME,clock:context.clock,authorizedAggregateChecksum:snapshot.aggregateChecksum});assert.equal((await refreshed.resume()).stage,'snapshot_verified')}
{const s=await throughOpening();const ready=await s.controller.readiness();assert.equal(ready.blockers.length,0);assert.equal((await s.persistence.getAll(V4_STORES.journalEntries)).length,0);assert.equal((await s.persistence.get(V4_STORES.migrationRuns,s.controller.state.run.id)).metadata.zeroOpeningPosition,true)}
{const s=await throughOpening(()=>true);await s.controller.acceptWarnings([...AUTHORIZED_WARNINGS]);await assert.rejects(s.controller.completeCutover(),/MAINTENANCE_MODE_NOT_ACTIVE/)}
{const s=await throughOpening(()=>false);await s.controller.acceptWarnings([...AUTHORIZED_WARNINGS]);await s.controller.activateMaintenance();await assert.rejects(s.controller.completeCutover(),/FINAL_HUMAN_CONFIRMATION_REQUIRED/);assert.equal(s.controller.state.run.status,'accepted')}
{const s=await throughOpening(()=>true);await s.controller.acceptWarnings([...AUTHORIZED_WARNINGS]);await s.controller.activateMaintenance();const completed=await s.controller.completeCutover(),verified=await s.controller.verify();assert.equal(completed.status,'cutover_completed');assert.equal(verified.status,'cutover_completed');assert.equal(verified.rollbackAvailable,true);assert.equal(verified.zeroOpeningPosition,true);assert.equal(verified.trialBalanceBalanced,true);assert.equal(verified.balanceSheetBalanced,true);assert.equal(completed.nativeOperationsStarted,false);const rolled=await s.controller.rollback('synthetic verification');assert.equal(rolled.status,'rolled_back')}
process.stdout.write('All focused V4 production cutover-control checks passed, including repeated snapshot import.\n');
