import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { V4_DATABASE_VERSION, V4_STORES, applyV4SchemaUpgrade } from '../v4/persistence/schema.mjs';
import { bootstrapLegacyV3Owner } from '../v4/authorization/repositories.mjs';
import { createV4Repositories, ScopeValidationError } from '../v4/persistence/repositories.mjs';
import { createInventoryService } from '../v4/inventory/inventory.mjs';
import { MemoryV4Persistence } from './helpers/memory-v4-persistence.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const clock = () => new Date('2026-08-17T16:00:00.000Z');
let seed = 100;
const cryptoApi = { getRandomValues(bytes) { seed += 1; bytes.forEach((_, i) => { bytes[i] = (seed + i) % 256; }); return bytes; } };
const context = { clock, uuidOptions: { timestamp: clock().getTime(), cryptoApi } };
async function test(name, fn) { try { await fn(); process.stdout.write(`PASS ${name}\n`); } catch (e) { process.stderr.write(`FAIL ${name}\n`); throw e; } }
function recorderV2() {
  const v2 = ['accounts','businesses','operatingUnits','legacyMappings','businessEvents','meta','users','businessMemberships','roles','permissions','roleAssignments','approvals'];
  const stores = new Map();
  const make = name => { const indexes = new Map(); const store = { marker: name, indexNames: { contains: x => indexes.has(x), [Symbol.iterator]: function*(){yield* indexes.keys();}}, createIndex:(n,k,o)=>indexes.set(n,{k,o}) }; stores.set(name,store); return store; };
  v2.forEach(make);
  return { stores, database:{ objectStoreNames:{contains:n=>stores.has(n),[Symbol.iterator]:function*(){yield* stores.keys();}},createObjectStore:make }, transaction:{objectStore:n=>stores.get(n)} };
}
async function setup() {
  const persistence = new MemoryV4Persistence();
  const owner = await bootstrapLegacyV3Owner(persistence, {}, context);
  const service = createInventoryService(persistence);
  const product = await service.createProduct({ businessId: owner.business.id, name: 'Test Product', defaultSellingPriceMinor: 200000, sellingCurrency: 'NGN' }, context);
  const location = await service.createLocation({ businessId: owner.business.id, operatingUnitId: owner.operatingUnit.id, name: 'Sales Floor' }, context);
  const merchant = await service.createOwnership({ businessId: owner.business.id, type: 'merchant' }, context);
  return { persistence, owner, service, product, location, merchant, base:createV4Repositories(persistence) };
}
globalThis.localStorage=Object.freeze({getItem(){throw Error('no V3 read')},setItem(){throw Error('no V3 write')},removeItem(){throw Error('no V3 write')},clear(){throw Error('no V3 write')}});

await test('upgrades v2 additively while preserving every earlier store',()=>{const r=recorderV2(),a=r.stores.get('accounts');applyV4SchemaUpgrade(r.database,r.transaction,2);assert.equal(V4_DATABASE_VERSION,7);assert.equal(r.stores.get('accounts'),a);assert.equal(r.stores.size,Object.values(V4_STORES).length);});
await test('creates Product and allows duplicate names with distinct IDs',async()=>{const s=await setup();const p=await s.service.createProduct({businessId:s.owner.business.id,name:'Test Product'},context);assert.notEqual(p.id,s.product.id);});
await test('supports multiple identifiers and rejects duplicate active identity',async()=>{const s=await setup();await s.service.addIdentifier({businessId:s.owner.business.id,productId:s.product.id,type:'barcode',value:'ABC'},context);await s.service.addIdentifier({businessId:s.owner.business.id,productId:s.product.id,type:'sku',value:'ABC'},context);await assert.rejects(s.service.addIdentifier({businessId:s.owner.business.id,productId:s.product.id,type:'barcode',value:'abc'},context),ScopeValidationError);});
await test('creates InventoryLocation under an Operating Unit',async()=>{const s=await setup();assert.equal(s.location.operatingUnitId,s.owner.operatingUnit.id);});
await test('records opening movement and derives location, unit, and Business stock',async()=>{const s=await setup();await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'opening',quantity:10},null,context);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,inventoryLocationId:s.location.id})).quantity,10);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,operatingUnitId:s.owner.operatingUnit.id})).quantity,10);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id})).quantity,10);});
await test('separates merchant, supplier, and unknown ownership stock',async()=>{const s=await setup();const supplier=await s.service.createOwnership({businessId:s.owner.business.id,type:'supplier_consignment',ownerReference:{type:'unresolved_supplier',id:'SUP-REF'}},context);const unknown=await s.service.createOwnership({businessId:s.owner.business.id,type:'unknown_historical'},context);for(const [o,q,t] of [[s.merchant,12,'opening'],[supplier,8,'consignment_receipt'],[unknown,3,'opening']])await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:o.id,movementType:t,quantity:q},null,context);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,ownershipType:'merchant'})).quantity,12);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,ownershipType:'supplier_consignment'})).quantity,8);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,ownershipType:'unknown_historical'})).quantity,3);});
await test('calculates weighted-average acquisition cost',async()=>{const s=await setup();for(const [q,c] of [[10,500000],[20,600000]])await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'purchase_receipt',quantity:q},{unitCostMinor:c,currency:'NGN'},context);assert.deepEqual(await s.service.weightedAverageCost({businessId:s.owner.business.id,productId:s.product.id,ownershipType:'merchant'}),{unitCostMinor:566667,costStatus:'known'});});
await test('preserves unknown cost and does not infer it from selling price',async()=>{const s=await setup();await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'opening',quantity:5},{unitCostMinor:null,currency:null},context);assert.equal((await s.service.weightedAverageCost({businessId:s.owner.business.id,productId:s.product.id})).costStatus,'unknown');});
await test('selling-price changes do not alter historical cost layers',async()=>{const s=await setup();await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'purchase_receipt',quantity:2},{unitCostMinor:50000,currency:'NGN'},context);await s.persistence.put(V4_STORES.products,{...s.product,defaultSellingPriceMinor:999999});assert.equal((await s.service.weightedAverageCost({businessId:s.owner.business.id,productId:s.product.id})).unitCostMinor,50000);});
await test('records stock adjustment and detects negative stock',async()=>{const s=await setup();await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'adjustment_decrease',quantity:2},null,context);assert.deepEqual((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id})).negative,true);});
await test('enforces prevent-negative location policy',async()=>{const s=await setup();const strict=await s.service.createLocation({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,name:'Strict',negativeStockPolicy:'prevent'},context);await assert.rejects(s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:strict.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'sale_issue',quantity:1},null,context),ScopeValidationError);});
await test('atomically transfers stock without changing Business total',async()=>{const s=await setup();const to=await s.service.createLocation({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,name:'Stock Room'},context);await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'opening',quantity:10},null,context);await s.service.transfer({businessId:s.owner.business.id,productId:s.product.id,ownershipId:s.merchant.id,quantity:4,fromLocationId:s.location.id,toLocationId:to.id,fromOperatingUnitId:s.owner.operatingUnit.id,toOperatingUnitId:s.owner.operatingUnit.id},context);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id})).quantity,10);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id,inventoryLocationId:to.id})).quantity,4);});
await test('rolls back both transfer movements and event on failure',async()=>{const s=await setup();const to=await s.service.createLocation({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,name:'B'},context);const before=(await s.persistence.getAll(V4_STORES.businessEvents)).length;await assert.rejects(s.service.transfer({businessId:s.owner.business.id,productId:s.product.id,ownershipId:s.merchant.id,quantity:1,fromLocationId:s.location.id,toLocationId:to.id,fromOperatingUnitId:s.owner.operatingUnit.id,toOperatingUnitId:s.owner.operatingUnit.id,deliberateFailure:true},context),/Deliberate/);assert.equal((await s.persistence.getAll(V4_STORES.inventoryMovements)).length,0);assert.equal((await s.persistence.getAll(V4_STORES.businessEvents)).length,before);});
await test('rejects cross-Business transfer',async()=>{const s=await setup();const b=await s.base.createBusiness({accountId:s.owner.account.id,name:'Other'},context),u=await s.base.createOperatingUnit({businessId:b.id,name:'Other Unit'},context),l=await s.service.createLocation({businessId:b.id,operatingUnitId:u.id,name:'Other Loc'},context);await assert.rejects(s.service.transfer({businessId:s.owner.business.id,productId:s.product.id,ownershipId:s.merchant.id,quantity:1,fromLocationId:s.location.id,toLocationId:l.id,fromOperatingUnitId:s.owner.operatingUnit.id,toOperatingUnitId:u.id},context),ScopeValidationError);});
await test('supports exact reversal and rejects invalid reversal',async()=>{const s=await setup();const {movement}=await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'opening',quantity:5},null,context);await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'reversal',quantity:5,signedQuantity:-5,reversalOfId:movement.id},null,context);assert.equal((await s.service.stock({businessId:s.owner.business.id,productId:s.product.id})).quantity,0);await assert.rejects(s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'reversal',quantity:4,signedQuantity:-4,reversalOfId:movement.id},null,context),ScopeValidationError);});
await test('generates compact Product, identifier, movement, transfer, and reversal events',async()=>{const s=await setup();await s.service.addIdentifier({businessId:s.owner.business.id,productId:s.product.id,type:'sku',value:'SKU1'},context);const {movement}=await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'opening',quantity:1},null,context);await s.service.recordMovement({businessId:s.owner.business.id,operatingUnitId:s.owner.operatingUnit.id,inventoryLocationId:s.location.id,productId:s.product.id,ownershipId:s.merchant.id,movementType:'reversal',quantity:1,signedQuantity:-1,reversalOfId:movement.id},null,context);const types=(await s.persistence.getAll(V4_STORES.businessEvents)).map(e=>e.eventType);for(const t of ['product.created','product.identifier_added','inventory.opened','inventory.reversed'])assert.equal(types.includes(t),true);});
await test('does not expose mutable stock balance or mutate V3',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(app,/const DATA_VERSION = 3;/);assert.equal(app.includes('v4/'),false);assert.equal(html.includes('v4/'),false);assert.equal(typeof globalThis.localStorage.setItem,'function');});
process.stdout.write('All V4 Phase 3 inventory checks passed.\n');
