import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createV4Application}from'../v4/application/application.mjs';import{createMigrationService}from'../v4/migration/migration.mjs';import{parseRehearsalSnapshot,REHEARSAL_DATABASE_NAME}from'../v4/migration/rehearsal-import.mjs';import{V3_STORAGE_KEYS}from'../v4/legacy/legacy-reader.mjs';import{V4_STORES}from'../v4/persistence/schema.mjs';import{MemoryV4Persistence}from'./helpers/memory-v4-persistence.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),context={clock:()=>new Date('2026-08-18T10:00:00Z'),uuidOptions:{now:()=>1776506400000,randomBytes:n=>new Uint8Array(n).fill(6)}},tests=[];const test=(name,fn)=>tests.push([name,fn]);
const raw=()=>({[V3_STORAGE_KEYS.inventory]:JSON.stringify([{id:'p1',name:'Rice',quantity:2,price:100}]),[V3_STORAGE_KEYS.customers]:'[]',[V3_STORAGE_KEYS.sales]:'[]',[V3_STORAGE_KEYS.payments]:'[]',[V3_STORAGE_KEYS.expenses]:'[]',[V3_STORAGE_KEYS.business]:JSON.stringify({name:'Legacy'}),[V3_STORAGE_KEYS.dataVersion]:'3'}),envelope=()=>({rawValues:raw(),createdBy:'operator',buildReference:'v3-checkpoint',createdAt:'2026-08-18T09:00:00Z'});
async function setup(source=raw()){const persistence=new MemoryV4Persistence(),app=await createV4Application({persistence,context,bootstrap:{businessName:'Rehearsal'}}),migration=createMigrationService(persistence,{context,cryptoApi:globalThis.crypto}),snapshot=await migration.createSnapshot({...envelope(),rawValues:source}),ctx=app.getContext(),run=await migration.createRun({snapshotId:snapshot.id,businessId:ctx.businessId,operatingUnitId:ctx.operatingUnitId,inventoryLocationId:ctx.inventoryLocationId,baseCurrency:ctx.baseCurrency,cutoverAt:'2026-09-01T00:00:00Z',actorId:'operator'});return{persistence,app,migration,snapshot,ctx,run}}
async function reconciled(source){const s=await setup(source);s.run=await s.migration.execute(s.run.id);s.reconciliation=await s.migration.reconcile(s.run.id);return s}
async function opening(s,receivables={status:'not_applicable',reason:'No opening receivables'},payables={status:'not_applicable',reason:'No opening payables'}){const cash=(await s.persistence.getAll(V4_STORES.ledgerAccounts)).find(x=>x.systemRole==='cash_on_hand');return s.migration.recordOpeningPosition(s.run.id,{actor:'operator',receivables,payables,balances:[{accountId:cash.id,amountMinor:100,verifiedAt:'2026-08-18T10:00:00Z',verificationReference:'cash count'}]},s.app.services.finance)}
test('valid seven-key JSON import',()=>{const parsed=parseRehearsalSnapshot(JSON.stringify(envelope()));assert.equal(Object.keys(parsed.rawValues).length,7);assert.equal(parsed.createdBy,'operator')});
test('missing key rejection',()=>{const value=envelope();delete value.rawValues[V3_STORAGE_KEYS.sales];assert.throws(()=>parseRehearsalSnapshot(JSON.stringify(value)),/key missing/)});
test('malformed JSON rejection',()=>assert.throws(()=>parseRehearsalSnapshot('{broken'),/valid JSON/));
test('invalid V3 version rejection',()=>{const value=envelope();value.rawValues[V3_STORAGE_KEYS.dataVersion]='4';assert.throws(()=>parseRehearsalSnapshot(JSON.stringify(value)),/version 3/)});
test('exact raw-value preservation',()=>{const value=envelope(),bytes=' { "untouched" : [ 1, 2 ] } ';value.rawValues[V3_STORAGE_KEYS.inventory]=bytes;assert.equal(parseRehearsalSnapshot(JSON.stringify(value)).rawValues[V3_STORAGE_KEYS.inventory],bytes)});
test('dedicated database name cannot alias normal V4',()=>assert.equal(REHEARSAL_DATABASE_NAME,'freeofis_v4_phase8_operator_rehearsal'));
test('successful synthetic workflow reaches accepted',async()=>{const s=await reconciled();await opening(s);const accepted=await s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:[...new Set(s.reconciliation.warnings.map(x=>x.code))]});assert.equal(accepted.status,'accepted')});
test('target blocker prevents acceptance',async()=>{const persistence=new MemoryV4Persistence(),app=await createV4Application({persistence,context}),migration=createMigrationService(persistence,{context}),created=await app.createProduct({name:'Native'}),snapshot=await migration.createSnapshot(envelope()),ctx=app.getContext(),run=await migration.createRun({snapshotId:snapshot.id,businessId:ctx.businessId,operatingUnitId:ctx.operatingUnitId,inventoryLocationId:ctx.inventoryLocationId,baseCurrency:ctx.baseCurrency,cutoverAt:'2026-09-01T00:00:00Z',actorId:'operator'});assert.equal(created.ok,true);assert.equal(run.status,'preview');await assert.rejects(migration.accept(run.id,{actor:'operator'}))});
test('unresolved AR prevents acceptance',async()=>{const s=await reconciled();await opening(s,{status:'unresolved',reason:'Awaiting confirmation'});await assert.rejects(s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:[...new Set(s.reconciliation.warnings.map(x=>x.code))]}),/verified_opening_ar/)});
test('unresolved AP prevents acceptance',async()=>{const s=await reconciled();await opening(s,undefined,{status:'unresolved',reason:'Awaiting confirmation'});await assert.rejects(s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:[...new Set(s.reconciliation.warnings.map(x=>x.code))]}),/verified_opening_ap/)});
test('operator UI exposes no maintenance or cutover invocation controls',()=>{const html=fs.readFileSync(path.join(root,'v4/migration/rehearsal.html'),'utf8'),ui=fs.readFileSync(path.join(root,'v4/migration/rehearsal-ui.mjs'),'utf8');assert.equal(/activateMaintenanceMode|completeCutover|markNativeOperationsStarted/.test(html+ui),false);assert.match(html,/Isolated rehearsal only/)});
let failed=0;for(const[name,fn]of tests)try{await fn();process.stdout.write(`PASS ${name}\n`)}catch(error){failed++;process.stderr.write(`FAIL ${name}: ${error.stack||error}\n`)}if(failed)process.exitCode=1;else process.stdout.write(`All ${tests.length} V4 Phase 8 rehearsal checks passed.\n`);
