import assert from'node:assert/strict';
import{createV4Application}from'../v4/application/application.mjs';
import{createMigrationService}from'../v4/migration/migration.mjs';
import{V3_STORAGE_KEYS}from'../v4/legacy/legacy-reader.mjs';
import{V4_STORES}from'../v4/persistence/schema.mjs';
import{MemoryV4Persistence}from'./helpers/memory-v4-persistence.mjs';

const stamp='2026-08-18T21:30:00Z',context={clock:()=>new Date(stamp)},raw=()=>({[V3_STORAGE_KEYS.dataVersion]:'3',[V3_STORAGE_KEYS.inventory]:'[{"id":"p1","name":"Stock","quantity":1,"price":771000}]',[V3_STORAGE_KEYS.customers]:'[]',[V3_STORAGE_KEYS.sales]:'[]',[V3_STORAGE_KEYS.payments]:'[]',[V3_STORAGE_KEYS.expenses]:'[]',[V3_STORAGE_KEYS.business]:'{"name":"Legacy"}'});
async function migrated(){const persistence=new MemoryV4Persistence(),app=await createV4Application({persistence,context,bootstrap:{businessName:'Zero Opening'}}),migration=createMigrationService(persistence,{context,cryptoApi:globalThis.crypto}),snapshot=await migration.createSnapshot({rawValues:raw(),createdBy:'operator'}),ctx=app.getContext();let run=await migration.createRun({snapshotId:snapshot.id,businessId:ctx.businessId,operatingUnitId:ctx.operatingUnitId,inventoryLocationId:ctx.inventoryLocationId,baseCurrency:'NGN',cutoverAt:stamp,actorId:'operator'});run=await migration.execute(run.id);const reconciliation=await migration.reconcile(run.id);return{persistence,app,migration,run:reconciliation.run,reconciliation,ctx}}
async function zeroInput(s,overrides={}){const accounts=await s.persistence.getAll(V4_STORES.ledgerAccounts),cash=accounts.find(x=>x.systemRole==='cash_on_hand'),ar=accounts.find(x=>x.systemRole==='accounts_receivable'),ap=accounts.find(x=>x.systemRole==='accounts_payable'),reference='independently verified zero';return{actor:'operator',receivables:{status:'verified',amountMinor:0,verifiedAt:stamp,verificationReference:reference},payables:{status:'verified',amountMinor:0,verifiedAt:stamp,verificationReference:reference},balances:[{accountId:cash.id,amountMinor:0,verifiedAt:stamp,verificationReference:reference},{accountId:ar.id,amountMinor:0,verifiedAt:stamp,verificationReference:reference},{accountId:ap.id,amountMinor:0,verifiedAt:stamp,verificationReference:reference}],...overrides}}
const warnings=s=>[...new Set(s.reconciliation.warnings.map(x=>x.code))];

{const s=await migrated(),result=await s.migration.recordOpeningPosition(s.run.id,await zeroInput(s),s.app.services.finance),run=await s.persistence.get(V4_STORES.migrationRuns,s.run.id),tb=await s.app.services.finance.trialBalance(s.ctx.businessId),bs=await s.app.services.finance.balanceSheet(s.ctx.businessId),coverage=(await s.persistence.getAll(V4_STORES.migrationReconciliations)).find(x=>x.migrationRunId===s.run.id&&x.reconciliationType==='inventory_valuation_coverage');assert.equal(result.zeroOpeningPosition,true);assert.equal(run.metadata.zeroOpeningPosition,true);assert.equal(run.metadata.openingJournalId,undefined);assert.equal((await s.persistence.getAll(V4_STORES.journalEntries)).length,0);assert.equal((await s.persistence.getAll(V4_STORES.journalEntryLines)).length,0);assert.deepEqual([tb.totalDebitsMinor,tb.totalCreditsMinor,tb.balanced],[0,0,true]);assert.deepEqual([bs.assetsMinor,bs.liabilitiesAndEquityMinor,bs.balanced],[0,0,true]);assert.equal(run.metadata.openingVerification.inventoryValuation.status,'unknown');assert.equal(run.metadata.openingVerification.inventoryValuation.posted,false);assert.equal(coverage.unknownOrUnreconciled,1);assert.equal((await s.persistence.getAll(V4_STORES.inventoryCostLayers)).length,0);const accepted=await s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:warnings(s)});assert.equal(accepted.status,'accepted')}

{const s=await migrated(),input=await zeroInput(s);input.balances[0].verificationReference='';await assert.rejects(s.migration.recordOpeningPosition(s.run.id,input,s.app.services.finance),/verified cash/);await assert.rejects(s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:warnings(s)}),/opening|ready/i);assert.equal((await s.persistence.getAll(V4_STORES.journalEntries)).length,0)}

{const s=await migrated(),input=await zeroInput(s);input.balances[0].amountMinor=1;const batch=await s.migration.recordOpeningPosition(s.run.id,input,s.app.services.finance),run=await s.persistence.get(V4_STORES.migrationRuns,s.run.id);assert.ok(batch.journalEntryId);assert.equal(run.metadata.zeroOpeningPosition,false);assert.equal((await s.persistence.getAll(V4_STORES.journalEntries)).length,1);assert.ok((await s.persistence.getAll(V4_STORES.journalEntryLines)).every(x=>(x.debitMinor>0)!==(x.creditMinor>0)))}

{const s=await migrated();await s.migration.recordOpeningPosition(s.run.id,await zeroInput(s),s.app.services.finance);await s.migration.accept(s.run.id,{actor:'operator',acceptedWarnings:warnings(s)});await s.migration.activateMaintenanceMode(s.run.id,{actor:'operator',frozenAt:stamp,freezeReference:'zero-opening-test'});const run=await s.persistence.get(V4_STORES.migrationRuns,s.run.id);run.metadata.openingVerification.cash.verificationReference='';await s.persistence.put(V4_STORES.migrationRuns,run);const ready=await s.migration.readiness(s.run.id);assert.equal(ready.readyForCutover,false);assert.ok(ready.blockers.some(x=>x.code==='OPENING_JOURNAL_INVALID'||x.code==='OPENING_BALANCES_UNVERIFIED'));await assert.rejects(s.migration.completeCutover(s.run.id,{actor:'operator'}),/OPENING_JOURNAL_INVALID|OPENING_BALANCES_UNVERIFIED/);assert.equal((await s.persistence.get(V4_STORES.migrationRuns,s.run.id)).status,'accepted')}

process.stdout.write('All focused Phase 8 zero-opening-position checks passed.\n');
