import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createV5Platform}from'../v5/platform/platform.mjs';import{createExperienceServices}from'../v5/experience/experience.mjs';import{V5_DATABASE_NAME,V5_DATABASE_VERSION,V5_STORES,applyV5SchemaUpgrade}from'../v5/persistence/schema.mjs';import{MemoryV5Persistence}from'./helpers/memory-v5-persistence.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),scope=w=>({ownerType:w.ownerType,ownerId:w.ownerId,organisationId:w.organisationId,unitId:w.unitId,workspaceId:w.id});
async function base(){const persistence=new MemoryV5Persistence(),platform=await createV5Platform({persistence,cryptoApi:crypto}),teacher=await platform.registerUser({displayName:'Teacher'}),token=await platform.sessions.create(teacher.user.id),org=await platform.createOrganisation(token,{name:'Audit School',rootUnitName:'Main'}),school=await platform.activateWorkspace(token,{definitionId:'standard:school',ownerType:'organisation',ownerId:org.organisation.id,organisationId:org.organisation.id,unitId:org.rootUnit.id}),schoolScope=scope(school);await platform.school.setExperience(token,{...schoolScope,userId:teacher.user.id,experienceRole:'lecturer'});async function student(name){const registered=await platform.registerUser({displayName:name}),studentToken=await platform.sessions.create(registered.user.id);await platform.addMembership(token,{userId:registered.user.id,organisationId:org.organisation.id,roleCode:'member'});await platform.school.setExperience(studentToken,{...schoolScope,userId:registered.user.id,experienceRole:'student'});return{user:registered.user,token:studentToken}}return{persistence,platform,teacher:teacher.user,token,org,school,schoolScope,student}}
assert.equal(V5_DATABASE_NAME,'freeofis_v5');assert.equal(V5_DATABASE_VERSION,8);
// Fresh V5 starts from platform services alone, with personal Space and organisation flows independent of V3/V4.
{const persistence=new MemoryV5Persistence(),platform=await createV5Platform({persistence,cryptoApi:crypto}),user=await platform.registerUser({displayName:'Fresh User'}),token=await platform.sessions.create(user.user.id),space=await platform.activateWorkspace(token,{definitionId:'standard:space',ownerType:'personal',ownerId:user.user.id}),org=await platform.createOrganisation(token,{name:'Fresh Organisation'});assert.equal((await platform.listContexts(token)).some(x=>x.kind==='personal'),true);assert.equal((await platform.getWorkspace(token,space.id)).ownerType,'personal');assert.equal((await platform.listContexts(token)).some(x=>x.organisationId===org.organisation.id),true)}
// Existing stores receive newly declared indexes during additive upgrades; no reset is required.
{const created=[],existingStore={indexNames:{contains:name=>name==='byOwner'},createIndex(name){created.push(name)}},database={objectStoreNames:{contains:name=>name==='people'},createObjectStore(){return{indexNames:{contains:()=>false},createIndex(){}}}},transaction={objectStore:name=>{assert.equal(name,'people');return existingStore}};applyV5SchemaUpgrade(database,transaction);assert.ok(created.includes('byOrganisationId'));assert.ok(created.includes('byWorkspaceId'));assert.equal(created.includes('byOwner'),false)}
// A School member cannot self-elevate to Lecturer or use the generic School getter as a cross-domain read primitive.
{const s=await base(),a=await s.student('Student A'),business=await s.platform.activateWorkspace(s.token,{definitionId:'standard:business',ownerType:'organisation',ownerId:s.org.organisation.id,organisationId:s.org.organisation.id,unitId:s.org.rootUnit.id}),businessService=await s.platform.loadBusiness(),businessScope={organisationId:s.org.organisation.id,workspaceId:business.id,unitId:s.org.rootUnit.id};await businessService.configure(s.token,{...businessScope,currency:'NGN'});const customer=await businessService.createCustomer(s.token,{...businessScope,name:'Private Customer'});await assert.rejects(s.platform.school.setExperience(a.token,{...s.schoolScope,userId:a.user.id,experienceRole:'lecturer'}),/SCHOOL_ACCESS_DENIED/);await assert.rejects(s.platform.school.get(a.token,V5_STORES.businessCustomers,customer.id),/ENTITY_TYPE_DENIED/)}
// Student shared Tasks, Notes, course Events and Ink/Capture are audience-filtered through every shared entry point.
{const s=await base(),a=await s.student('Student A'),b=await s.student('Student B'),course=await s.platform.school.createCourse(s.token,{...s.schoolScope,title:'Economics',lecturerUserIds:[s.teacher.id]});await s.platform.school.enroll(s.token,{...s.schoolScope,courseId:course.id,studentUserId:a.user.id});const assignment=await s.platform.school.createAssignment(s.token,{...s.schoolScope,title:'Private Essay',courseId:course.id,studentUserIds:[a.user.id],dueAt:'2026-08-20T12:00:00.000Z'}),note=await s.platform.sharedWork.create(a.token,'note',{...s.schoolScope,title:'Student A private note',content:'private'}),lesson=await s.platform.school.createClass(s.token,{...s.schoolScope,courseId:course.id,title:'Economics class',startAt:'2026-08-21T10:00:00.000Z'}),ink=await s.platform.capture.createInk(a.token,{...s.schoolScope,title:'Student A ink',width:10,height:10,strokes:[{points:[{x:1,y:1},{x:2,y:2}]}]});assert.equal((await s.platform.sharedWork.list(a.token,'task',s.schoolScope)).some(x=>assignment.taskIds.includes(x.id)),true);assert.equal((await s.platform.sharedWork.list(b.token,'task',s.schoolScope)).some(x=>assignment.taskIds.includes(x.id)),false);await assert.rejects(s.platform.sharedWork.get(b.token,'note',note.id),/ACCESS_DENIED/);assert.equal((await s.platform.sharedWork.list(b.token,'event',s.schoolScope)).some(x=>x.id===lesson.id),false);await assert.rejects(s.platform.capture.getInk(b.token,ink.ink.id),/CAPTURE_ACCESS_DENIED/)}
// Draft Results remain inaccessible directly; lecturer result views are limited to courses they teach.
{const s=await base(),a=await s.student('Student A'),course=await s.platform.school.createCourse(s.token,{...s.schoolScope,title:'Economics',lecturerUserIds:[s.teacher.id]});await s.platform.school.enroll(s.token,{...s.schoolScope,courseId:course.id,studentUserId:a.user.id});const result=await s.platform.school.recordResult(s.token,{...s.schoolScope,studentUserId:a.user.id,courseId:course.id,score:70});await assert.rejects(s.platform.school.get(a.token,V5_STORES.results,result.id),/SCHOOL_ACCESS_DENIED/);await s.platform.school.releaseResult(s.token,result.id);assert.equal((await s.platform.school.get(a.token,V5_STORES.results,result.id)).id,result.id)}
// Office correspondence links use their real endpoint type and pass the non-mutating integrity checker.
{const s=await base(),office=await s.platform.activateWorkspace(s.token,{definitionId:'standard:office',ownerType:'organisation',ownerId:s.org.organisation.id,organisationId:s.org.organisation.id,unitId:s.org.rootUnit.id}),officeScope=scope(office),item=await s.platform.office.createCorrespondence(s.token,{...officeScope,direction:'incoming',subject:'Generator request',partyName:'Branch',actionRequired:'Review'});await s.platform.office.createTaskFromCorrespondence(s.token,item.id);await s.platform.office.transitionCorrespondence(s.token,item.id,'closed');await s.platform.office.retainCorrespondence(s.token,item.id);const links=await s.persistence.getAll(V5_STORES.relationships);assert.equal(links.filter(x=>x.targetId===item.id).every(x=>x.targetType==='officeCorrespondence'),true);assert.equal((await s.platform.integration.checkIntegrity(s.token,{ownerType:'organisation',ownerId:s.org.organisation.id,organisationId:s.org.organisation.id})).valid,true)}
// My Day is chronological and de-duplicated; Quick Create removes same-workspace duplicate actions.
{const s=await base(),services=createExperienceServices(s.platform),context=(await s.platform.listContexts(s.token)).find(x=>x.organisationId===s.org.organisation.id&&!x.unitId);services.myDay.registerProvider({id:'one',provide:async()=>[{...s.schoolScope,id:'later',kind:'task',title:'Later',dueAt:'2026-08-20T15:00:00.000Z'},{...s.schoolScope,id:'same',kind:'task',title:'Same',dueAt:'2026-08-20T13:00:00.000Z'}]});services.myDay.registerProvider({id:'two',provide:async()=>[{...s.schoolScope,id:'same',kind:'task',title:'Same duplicate',dueAt:'2026-08-20T13:00:00.000Z'},{...s.schoolScope,id:'first',kind:'event',title:'First',startAt:'2026-08-20T09:00:00.000Z'}]});services.quickCreate.registerProvider({id:'generic',provide:async()=>[{...s.schoolScope,id:'g',label:'Task'}]});services.quickCreate.registerProvider({id:'school',provide:async()=>[{...s.schoolScope,id:'s',label:'Task'}]});assert.deepEqual((await services.myDay.list(s.token,context)).map(x=>x.id),['first','same','later']);assert.deepEqual((await services.quickCreate.list(s.token,context)).map(x=>x.id),['s'])}
// Startup stays lazy, local and free of secrets/debug hooks; responsive and accessibility foundations remain present.
{const main=fs.readFileSync(path.join(root,'v5/app/main.mjs'),'utf8'),html=fs.readFileSync(path.join(root,'v5/app/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'v5/app/styles.css'),'utf8'),production=fs.readdirSync(path.join(root,'v5'),{recursive:true}).filter(x=>/\.(?:mjs|js)$/.test(x)).map(x=>fs.readFileSync(path.join(root,'v5',x),'utf8')).join('\n');assert.match(main,/import\('\.\.\/workspaces\/business\/landing\.mjs'\)/);assert.doesNotMatch(main,/from '..\/platform\/business\.mjs'/);assert.doesNotMatch(production,/console\.(?:log|debug)|debugger|BEGIN (?:RSA |EC )?PRIVATE KEY|AIza[0-9A-Za-z_-]{20,}/);assert.match(html,/<main[^>]+id="content"/);assert.match(html,/Skip to content/);assert.match(css,/:focus-visible/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/@media\(max-width:48rem\)/);assert.doesNotMatch(production,/fetch\(|https?:\/\//)}
process.stdout.write('All Free Ofis V5 Phase 12 audit, privacy hardening, schema upgrade, aggregation, startup, and hygiene checks passed.\n');
