import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createScopedRecord, isId } from '../v5/domain/foundation.mjs';
import { createV5Platform } from '../v5/platform/platform.mjs';
import { V5_DATABASE_NAME, V5_DATABASE_VERSION, V5_STORES } from '../v5/persistence/schema.mjs';
import { STANDARD_WORKSPACES } from '../v5/security/catalog.mjs';
import { MemoryV5Persistence } from './helpers/memory-v5-persistence.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),stamp='2026-08-19T09:00:00.000Z',context={clock:()=>new Date(stamp)};
async function setup(){const persistence=new MemoryV5Persistence(),platform=await createV5Platform({persistence,context,cryptoApi:globalThis.crypto}),registered=await platform.registerUser({displayName:'Owner',email:`owner-${crypto.randomUUID()}@example.test`}),token=await platform.sessions.create(registered.user.id);return{persistence,platform,...registered,token}}
async function user(platform,name){const registered=await platform.registerUser({displayName:name,email:`${name}-${crypto.randomUUID()}@example.test`}),token=await platform.sessions.create(registered.user.id);return{...registered,token}}

assert.equal(V5_DATABASE_NAME,'freeofis_v5');assert.equal(V5_DATABASE_VERSION,5);assert.doesNotMatch(fs.readFileSync(path.join(root,'v5/platform/platform.mjs'),'utf8')+fs.readFileSync(path.join(root,'v5/persistence/schema.mjs'),'utf8'),/v3|v4|freeofis_v4|localStorage/i);

// Registry and fresh persistence.
{const s=await setup(),definitions=await s.persistence.getAll(V5_STORES.workspaceDefinitions);assert.deepEqual(definitions.filter(x=>x.standard).map(x=>x.code).sort(),STANDARD_WORKSPACES.map(x=>x.code).sort());assert.equal((await s.persistence.get(V5_STORES.meta,'platformFoundation')).databaseName,'freeofis_v5')}

// Scenario A: individual and personal ownership are structurally separate.
{const s=await setup(),space=await s.platform.activateWorkspace(s.token,{definitionId:'standard:space',ownerType:'personal',ownerId:s.user.id,name:'Private Space'});assert.equal(space.organisationId,null);assert.equal((await s.platform.getWorkspace(s.token,space.id)).id,space.id);const outsider=await user(s.platform,'Outsider');await assert.rejects(s.platform.getWorkspace(outsider.token,space.id),/WORKSPACE_ACCESS_DENIED/)}

// Scenarios B/C/D: generic organisations can activate Business, Office and School without separate infrastructure.
{const s=await setup(),small=await s.platform.createOrganisation(s.token,{name:'Small Business',organisationType:'business'});for(const code of['business'])assert.ok(await s.platform.activateWorkspace(s.token,{definitionId:`standard:${code}`,ownerType:'organisation',ownerId:small.organisation.id,organisationId:small.organisation.id,unitId:small.rootUnit.id}));const company=await s.platform.createOrganisation(s.token,{name:'Company',organisationType:'company'});for(const code of['office','business'])assert.ok(await s.platform.activateWorkspace(s.token,{definitionId:`standard:${code}`,ownerType:'organisation',ownerId:company.organisation.id,organisationId:company.organisation.id,unitId:company.rootUnit.id}));const school=await s.platform.createOrganisation(s.token,{name:'School',organisationType:'school'});for(const code of['office','business','school'])assert.ok(await s.platform.activateWorkspace(s.token,{definitionId:`standard:${code}`,ownerType:'organisation',ownerId:school.organisation.id,organisationId:school.organisation.id,unitId:school.rootUnit.id}))}

// Scenario E and unit isolation: hierarchy permits assigned descendants, never siblings.
{const s=await setup(),ministry=await s.platform.createOrganisation(s.token,{name:'Ministry',organisationType:'ministry'}),abuja=await s.platform.createUnit(s.token,{organisationId:ministry.organisation.id,parentUnitId:ministry.rootUnit.id,name:'Abuja Directorate',unitType:'directorate'}),abujaTeam=await s.platform.createUnit(s.token,{organisationId:ministry.organisation.id,parentUnitId:abuja.id,name:'Abuja Team',unitType:'team'}),kano=await s.platform.createUnit(s.token,{organisationId:ministry.organisation.id,parentUnitId:ministry.rootUnit.id,name:'Kano Directorate',unitType:'directorate'}),manager=await user(s.platform,'Manager'),membership=await s.platform.addMembership(s.token,{userId:manager.user.id,organisationId:ministry.organisation.id,roleCode:'manager',scopeType:'units',unitIds:[abuja.id]});assert.equal(await s.platform.can({userId:manager.user.id,organisationId:ministry.organisation.id,unitId:abuja.id,permissionCode:'units.manage'}),true);assert.equal(await s.platform.can({userId:manager.user.id,organisationId:ministry.organisation.id,unitId:abujaTeam.id,permissionCode:'units.manage'}),true);assert.equal(await s.platform.can({userId:manager.user.id,organisationId:ministry.organisation.id,unitId:kano.id,permissionCode:'units.manage'}),false);await s.platform.changeRole(s.token,{membershipId:membership.membership.id,organisationId:ministry.organisation.id,roleCode:'member',scopeType:'units',unitIds:[abuja.id]});assert.equal(await s.platform.can({userId:manager.user.id,organisationId:ministry.organisation.id,unitId:abuja.id,permissionCode:'units.manage'}),false)}

// Scenario F and tenant isolation: one identity, two memberships, no cross-organisation leakage.
{const s=await setup(),second=await user(s.platform,'MultiOrg'),a=await s.platform.createOrganisation(s.token,{name:'Org A'}),b=await s.platform.createOrganisation(s.token,{name:'Org B'});await s.platform.addMembership(s.token,{userId:second.user.id,organisationId:a.organisation.id,roleCode:'member'});await s.platform.addMembership(s.token,{userId:second.user.id,organisationId:b.organisation.id,roleCode:'manager',scopeType:'units',unitIds:[b.rootUnit.id]});assert.equal(await s.platform.can({userId:second.user.id,organisationId:a.organisation.id,permissionCode:'organisation.view'}),true);assert.equal(await s.platform.can({userId:second.user.id,organisationId:a.organisation.id,permissionCode:'organisation.manage'}),false);assert.equal(await s.platform.can({userId:second.user.id,organisationId:b.organisation.id,unitId:b.rootUnit.id,permissionCode:'units.manage'}),true);const stranger=await user(s.platform,'Stranger');assert.equal(await s.platform.can({userId:stranger.user.id,organisationId:a.organisation.id,permissionCode:'organisation.view'}),false)}

// Organisation admins never inherit personal access.
{const s=await setup(),admin=await user(s.platform,'Admin'),org=await s.platform.createOrganisation(s.token,{name:'Privacy Org'});await s.platform.addMembership(s.token,{userId:admin.user.id,organisationId:org.organisation.id,roleCode:'admin'});const privateSpace=await s.platform.activateWorkspace(s.token,{definitionId:'standard:space',ownerType:'personal',ownerId:s.user.id});await assert.rejects(s.platform.getWorkspace(admin.token,privateSpace.id),/WORKSPACE_ACCESS_DENIED/)}

// Disabled workspace, missing ownership and cross-scope input fail closed.
{const s=await setup(),definition=await s.persistence.get(V5_STORES.workspaceDefinitions,'standard:studio');await s.persistence.put(V5_STORES.workspaceDefinitions,{...definition,status:'disabled'});await assert.rejects(s.platform.activateWorkspace(s.token,{definitionId:definition.id,ownerType:'personal',ownerId:s.user.id}),/WORKSPACE_DISABLED/);assert.throws(()=>createScopedRecord({createdByUserId:s.user.id}),/Owner type/);assert.equal(await s.platform.can({}),false)}

// IDs, custom workspace extension, sessions, and audit/activity foundations.
{const s=await setup(),org=await s.platform.createOrganisation(s.token,{name:'Extensible Org'}),custom=await s.platform.registerCustomWorkspace(s.token,{organisationId:org.organisation.id,code:`custom-${crypto.randomUUID()}`,name:'Case Work'}),workspace=await s.platform.activateWorkspace(s.token,{definitionId:custom.id,ownerType:'organisation',ownerId:org.organisation.id,organisationId:org.organisation.id,unitId:org.rootUnit.id});assert.ok([s.user.id,org.organisation.id,org.rootUnit.id,workspace.id].every(isId));assert.notEqual(org.organisation.id,org.organisation.name);assert.ok((await s.persistence.getAll(V5_STORES.activityEvents)).some(x=>x.eventType==='workspace.activated'));const audits=await s.persistence.getAll(V5_STORES.auditEvents);assert.ok(audits.some(x=>x.eventType==='workspace.custom_registered'));assert.ok(audits.every(x=>!JSON.stringify(x.metadata).match(/secret|password|token/i)));assert.equal((await s.persistence.getAll(V5_STORES.sessions))[0].secret,undefined);assert.equal((await s.platform.sessions.validate({sessionId:s.token.sessionId,secret:'wrong'})),null)}

// Related foundation writes are atomic when a later write fails.
{const zeroCrypto={subtle:globalThis.crypto.subtle,getRandomValues(array){array.fill(0);return array}},persistence=new MemoryV5Persistence(),platform=await createV5Platform({persistence,context:{clock:context.clock,idOptions:{timestamp:1,cryptoApi:zeroCrypto}},cryptoApi:zeroCrypto}),registered=await platform.registerUser({displayName:'Atomic Owner'}),token=await platform.sessions.create(registered.user.id);await assert.rejects(platform.createOrganisation(token,{name:'Must Roll Back'}),/Duplicate key/);assert.equal((await persistence.getAll(V5_STORES.organisations)).length,0);assert.equal((await persistence.getAll(V5_STORES.organisationUnits)).length,0);assert.equal((await persistence.getAll(V5_STORES.memberships)).length,0)}

process.stdout.write('All Free Ofis V5 Phase 1 foundation, extensibility, and security checks passed.\n');
