import assert from 'node:assert/strict';import {createV5Platform} from '../v5/platform/platform.mjs';import {createExperienceServices,registerSharedWorkProviders} from '../v5/experience/experience.mjs';import {applyV5SchemaUpgrade,V5_DATABASE_VERSION,V5_STORES,V5_STORE_DEFINITIONS} from '../v5/persistence/schema.mjs';import {MemoryV5Persistence} from './helpers/memory-v5-persistence.mjs';
const stamp='2026-08-19T10:00:00.000Z',context={clock:()=>new Date(stamp)};async function setup(){const persistence=new MemoryV5Persistence(),platform=await createV5Platform({persistence,context,cryptoApi:crypto}),registered=await platform.registerUser({displayName:'Owner'}),token=await platform.sessions.create(registered.user.id),org=await platform.createOrganisation(token,{name:'Alpha'}),workspace=await platform.activateWorkspace(token,{definitionId:'standard:office',ownerType:'organisation',ownerId:org.organisation.id,organisationId:org.organisation.id,unitId:org.rootUnit.id}),scope={ownerType:workspace.ownerType,ownerId:workspace.ownerId,organisationId:workspace.organisationId,unitId:workspace.unitId,workspaceId:workspace.id};return{persistence,platform,token,user:registered.user,org,workspace,scope}}
// Additive schema retains Phase 2 stores and introduces typed/indexed shared stores.
assert.equal(V5_DATABASE_VERSION,8);for(const name of['users','userPreferences','notifications','people','tasks','events','projects','notes','documents','files','records','relationships'])assert.ok(V5_STORE_DEFINITIONS.some(x=>x.name===name));
{const existing=new Set(['meta','users','userPreferences','notifications']),created=[];applyV5SchemaUpgrade({objectStoreNames:{contains:name=>existing.has(name)},createObjectStore(name){created.push(name);return{createIndex(){}}}});assert.ok(created.includes('tasks'));assert.ok(created.includes('relationships'));assert.ok(!created.includes('users'));assert.ok(!created.includes('notifications'))}
// People remain durable, distinct and contextual; no name merge or global visibility.
{const s=await setup(),a=await s.platform.sharedWork.create(s.token,'person',{...s.scope,displayName:'Aisha Bello',contextualRoles:['contact']}),b=await s.platform.sharedWork.create(s.token,'person',{...s.scope,displayName:'Aisha Bello',contextualRoles:['source']});assert.notEqual(a.id,b.id);assert.deepEqual(a.contextualRoles,['contact']);assert.deepEqual(b.contextualRoles,['source']);const outsider=await s.platform.registerUser({displayName:'Outsider'}),outsideToken=await s.platform.sessions.create(outsider.user.id);await assert.rejects(s.platform.sharedWork.get(outsideToken,'person',a.id),/ACCESS_DENIED/)}
// Tasks/events integrate with My Day and Search; completion removes task from My Day.
{const s=await setup(),task=await s.platform.sharedWork.create(s.token,'task',{...s.scope,title:'Submit brief',dueAt:stamp,assigneeUserIds:[s.user.id]}),event=await s.platform.sharedWork.create(s.token,'event',{...s.scope,title:'Planning meeting',startAt:stamp,participantPersonIds:[]}),services=createExperienceServices(s.platform),orgContext=(await s.platform.listContexts(s.token)).find(x=>x.organisationId===s.org.organisation.id&&!x.unitId);registerSharedWorkProviders(services,s.platform,{clock:context.clock});assert.deepEqual((await services.myDay.list(s.token,orgContext)).map(x=>x.kind).sort(),['event','task']);assert.deepEqual((await services.search.search(s.token,orgContext,'brief')).map(x=>x.id),[task.id]);assert.ok((await services.quickCreate.list(s.token,orgContext)).some(x=>x.label==='Task'));assert.equal((await s.platform.sharedWork.completeTask(s.token,task.id)).completionState,'completed');assert.deepEqual((await services.myDay.list(s.token,orgContext)).map(x=>x.id),[event.id])}
// Every shared entity is reusable and documents, files and retained records stay structurally distinct.
{const s=await setup(),project=await s.platform.sharedWork.create(s.token,'project',{...s.scope,title:'Launch'}),note=await s.platform.sharedWork.create(s.token,'note',{...s.scope,title:'Decision',content:'Proceed'}),document=await s.platform.sharedWork.create(s.token,'document',{...s.scope,title:'Approved plan',documentType:'plan'}),file1=await s.platform.sharedWork.create(s.token,'file',{...s.scope,filename:'plan.pdf',displayName:'Plan PDF',mediaType:'application/pdf',size:20}),file2=await s.platform.sharedWork.create(s.token,'file',{...s.scope,filename:'plan.docx',displayName:'Plan source',mediaType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',size:30}),record=await s.platform.sharedWork.create(s.token,'record',{...s.scope,title:'Final approval',recordType:'decision',provenance:{origin:'derived',sourceType:'document',sourceId:document.id},retention:{classification:'official'}});for(const target of[file1,file2])await s.platform.sharedWork.relate(s.token,{...s.scope,sourceType:'document',sourceId:document.id,targetType:'file',targetId:target.id,relationshipType:'has_file',provenance:{origin:'linked'}});await s.platform.sharedWork.relate(s.token,{...s.scope,sourceType:'project',sourceId:project.id,targetType:'note',targetId:note.id,relationshipType:'has_note'});assert.equal((await s.platform.sharedWork.relationships(s.token,'document',document.id)).length,2);assert.equal(record.provenance.sourceId,document.id);assert.equal(record.retention.classification,'official');assert.notEqual(document.id,file1.id);assert.notEqual(record.id,document.id);assert.equal((await s.platform.sharedWork.archive(s.token,'record',record.id)).status,'archived');assert.ok((await s.persistence.getAll(V5_STORES.auditEvents)).some(x=>x.eventType==='record.archived'))}
// Cross-organisation and disabled-workspace writes/relationships fail closed.
{const s=await setup(),other=await s.platform.createOrganisation(s.token,{name:'Beta'}),otherWorkspace=await s.platform.activateWorkspace(s.token,{definitionId:'standard:business',ownerType:'organisation',ownerId:other.organisation.id,organisationId:other.organisation.id,unitId:other.rootUnit.id}),otherScope={ownerType:otherWorkspace.ownerType,ownerId:otherWorkspace.ownerId,organisationId:otherWorkspace.organisationId,unitId:otherWorkspace.unitId,workspaceId:otherWorkspace.id},left=await s.platform.sharedWork.create(s.token,'note',{...s.scope,title:'Alpha only'}),right=await s.platform.sharedWork.create(s.token,'note',{...otherScope,title:'Beta only'});await assert.rejects(s.platform.sharedWork.relate(s.token,{...s.scope,sourceType:'note',sourceId:left.id,targetType:'note',targetId:right.id,relationshipType:'references'}),/RELATIONSHIP_SCOPE_DENIED/);const definition=await s.persistence.get(V5_STORES.workspaceDefinitions,'standard:office');await s.persistence.put(V5_STORES.workspaceDefinitions,{...definition,status:'disabled'});await assert.rejects(s.platform.sharedWork.create(s.token,'task',{...s.scope,title:'Blocked'}),/WORKSPACE_DISABLED/)}
// Related writes are atomic when the audit/activity write fails.
{const s=await setup(),original=s.persistence.runTransaction.bind(s.persistence),before=(await s.persistence.getAll(V5_STORES.tasks)).length;s.persistence.runTransaction=async(names,mode,work)=>original(names,mode,async tx=>work({...tx,add:async(name,value)=>{if(name===V5_STORES.activityEvents&&value.eventType==='task.created')throw Error('injected failure');return tx.add(name,value)}}));await assert.rejects(s.platform.sharedWork.create(s.token,'task',{...s.scope,title:'Rollback'}),/injected failure/);assert.equal((await s.persistence.getAll(V5_STORES.tasks)).length,before)}
process.stdout.write('All Free Ofis V5 Phase 3 shared-work, integration, privacy, schema, and atomicity checks passed.\n');
