import { createV5Platform } from '../platform/platform.mjs';
import { createExperienceServices, registerCaptureProviders, registerOfficeProviders, registerSharedWorkProviders } from '../experience/experience.mjs';
import { detectCaptureCapabilities } from '../capture/browser-capabilities.mjs';
import { registerSchoolProviders } from '../experience/school.mjs';
import { registerStudioProviders } from '../experience/studio.mjs';
import { registerSpaceProviders } from '../experience/space.mjs';
import { registerBusinessProviders } from '../experience/business.mjs';
import { greetingForHour,parseRoute } from '../experience/shell-model.mjs';
const officeStyles=document.createElement('link');officeStyles.rel='stylesheet';officeStyles.href='./office.css';document.head.append(officeStyles);
const content=document.querySelector('#content'),contextSelect=document.querySelector('#context'),panel=document.querySelector('#panel'),panelContent=document.querySelector('#panel-content'),welcome=document.querySelector('#welcome');let platform,services,token,profile,context,workspaces=[];
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function start(){platform=await createV5Platform({indexedDB});services=createExperienceServices(platform);registerSharedWorkProviders(services,platform);const capabilities=detectCaptureCapabilities();registerCaptureProviders(services,platform,{capabilities});registerOfficeProviders(services,platform);registerSchoolProviders(services,platform);registerStudioProviders(services,platform,{capabilities});registerSpaceProviders(services,platform,{capabilities});registerBusinessProviders(services,platform);token=JSON.parse(sessionStorage.getItem('freeofis_v5_session')||'null');if(token)try{profile=await platform.getProfile(token)}catch{token=null;sessionStorage.removeItem('freeofis_v5_session')}if(!token){welcome.showModal();return}await refresh()}
async function refresh(){const contexts=await platform.listContexts(token);context=await platform.getActiveContext(token);contextSelect.innerHTML=contexts.map(item=>`<option value="${escape(item.key)}" ${item.key===context.key?'selected':''}>${escape(item.label)}${item.detail?` — ${escape(item.detail)}`:''}</option>`).join('');workspaces=await platform.listAvailableWorkspaces(token,context);await render()}
async function render(){const route=parseRoute(location.hash);if(route.page==='workspace'){const item=workspaces.find(({workspace})=>workspace.id===route.id);if(!item){location.hash='home';return}if(item.definition.type==='office'){const {renderOfficeLanding}=await import('../workspaces/office/landing.mjs');await renderOfficeLanding(content,{platform,token,...item,context});return}if(item.definition.type==='school'){const {renderSchoolLanding}=await import('../workspaces/school/landing.mjs');await renderSchoolLanding(content,{platform,token,...item,context});return}if(item.definition.type==='studio'){const {renderStudioLanding}=await import('../workspaces/studio/landing.mjs');await renderStudioLanding(content,{platform,token,...item,context});return}if(item.definition.type==='space'){const {renderSpaceLanding}=await import('../workspaces/space/landing.mjs');await renderSpaceLanding(content,{platform,token,...item,context});return}if(item.definition.type==='business'){const {renderBusinessLanding}=await import('../workspaces/business/landing.mjs');await renderBusinessLanding(content,{platform,token,...item,context});return}const {renderWorkspaceLanding}=await import('../workspaces/landing.mjs');renderWorkspaceLanding(content,{...item,context});return}const day=await services.myDay.list(token,context),activity=await platform.recentActivity(token,context);content.innerHTML=`<section class="hero"><p class="eyebrow">${escape(context.label)}${context.detail?` · ${escape(context.detail)}`:''}</p><h1>${greetingForHour(new Date().getHours())}, ${escape(profile.user.displayName.split(' ')[0])}.</h1><p>Everything you can use, in one calm place.</p></section><section><h2>Your workspaces</h2><div class="workspace-grid">${workspaces.length?workspaces.map(({workspace,definition})=>`<a class="workspace-card" href="#workspace/${escape(workspace.id)}"><strong>${escape(workspace.name||definition.name)}</strong><p>${escape(definition.type)} workspace</p></a>`).join(''):'<p class="empty">No workspaces are enabled in this context yet.</p>'}</div></section><div class="home-grid"><section class="section"><h2>My Day</h2>${day.length?day.map(item=>`<div class="result">${escape(item.title)}</div>`).join(''):'<p class="empty">Nothing needs your attention today.</p>'}</section><section class="section"><h2>Recent activity</h2>${activity.length?activity.slice(0,4).map(item=>`<p>${escape(item.eventType.replaceAll('.',' '))}</p>`).join(''):'<p class="empty">Your recent work will appear here.</p>'}</section></div>`}
welcome.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.currentTarget),registered=await platform.registerUser({displayName:data.get('displayName'),email:data.get('email')||null});token=await platform.sessions.create(registered.user.id);sessionStorage.setItem('freeofis_v5_session',JSON.stringify(token));profile={user:registered.user,personalEnvironment:registered.personalEnvironment};await platform.activateWorkspace(token,{definitionId:'standard:space',ownerType:'personal',ownerId:registered.user.id});welcome.close();location.hash='home';await refresh()});
contextSelect.addEventListener('change',async()=>{context=await platform.setActiveContext(token,contextSelect.value);location.hash='home';await refresh()});addEventListener('hashchange',render);document.querySelector('.dialog-close').onclick=()=>panel.close();document.addEventListener('click',async event=>{const action=event.target.closest('[data-open]')?.dataset.open;if(!action||!token)return;if(action==='search')panelContent.innerHTML='<h2>Search</h2><label>Search Free Ofis<input id="search-input" type="search"></label><div id="search-results" class="empty">Start typing to search what you can access.</div>';if(action==='create'){const items=await services.quickCreate.list(token,context);panelContent.innerHTML=`<h2>Quick Create</h2>${items.length?items.map(x=>`<button>${escape(x.label)}</button>`).join(''):'<p class="empty">Creation actions will appear as your workspaces add them.</p>'}`}if(action==='notifications'){const items=await services.notifications.list(token,context);panelContent.innerHTML=`<h2>Notifications</h2>${items.length?items.map(x=>`<div class="result"><strong>${escape(x.title)}</strong><p>${escape(x.message)}</p></div>`).join(''):'<p class="empty">You’re all caught up.</p>'}`}if(action==='profile')panelContent.innerHTML=`<h2>${escape(profile.user.displayName)}</h2><p>${escape(profile.user.email||'No email added')}</p><h3>Current context</h3><p>${escape(context.label)}${context.detail?` — ${escape(context.detail)}`:''}</p>`;panel.showModal();if(action==='search')document.querySelector('#search-input').addEventListener('input',async e=>{const results=await services.search.search(token,context,e.target.value);document.querySelector('#search-results').innerHTML=results.length?results.map(x=>`<div class="result">${escape(x.title)}</div>`).join(''):'No results found.'})});
start().catch(error=>content.innerHTML=`<p role="alert">Free Ofis could not open: ${escape(error.message)}</p>`);addEventListener('beforeunload',()=>platform?.close());
