import { createEvent } from '../domain/foundation.mjs';
import { createRelationship, SHARED_ENTITY_TYPES, STORE_BY_TYPE } from '../domain/shared-work.mjs';
import { V5_STORES } from '../persistence/schema.mjs';
import { can, canAccessOwnership } from '../security/authorization.mjs';

const sharedFields={
  person:x=>({displayName:x.displayName,contextualRoles:x.contextualRoles,email:x.email,phone:x.phone}),
  task:x=>({title:x.title,description:x.description,priority:x.priority,dueAt:x.dueAt,assigneeUserIds:[]}),
  event:x=>({title:x.title,description:x.description,startAt:x.startAt,endAt:x.endAt,allDay:x.allDay,location:x.location,participantPersonIds:[]}),
  project:x=>({title:x.title,description:x.description,startDate:x.startDate,targetDate:x.targetDate,responsibleUserIds:[]}),
  note:x=>({title:x.title,content:x.content}),
  document:x=>({title:x.title,summary:x.summary,documentType:x.documentType,version:1}),
  record:x=>({title:x.title,recordType:x.recordType,reference:x.reference,recordedAt:x.recordedAt,retention:x.retention})
};
const storeByRelationshipType={...STORE_BY_TYPE,officeCorrespondence:V5_STORES.officeCorrespondence,officeDecision:V5_STORES.officeDecisions,businessCustomer:V5_STORES.businessCustomers,businessSupplier:V5_STORES.businessSuppliers,businessProduct:V5_STORES.businessProducts,sale:V5_STORES.salesOrders,purchase:V5_STORES.purchaseOrders,goodsReceipt:V5_STORES.goodsReceipts,supplierInvoice:V5_STORES.supplierInvoices,expense:V5_STORES.businessExpenses,journal:V5_STORES.businessJournalEntries};
const owns=(a,b)=>a.ownerType===b.ownerType&&a.ownerId===b.ownerId&&a.organisationId===b.organisationId;

export function createIntegrationService({persistence,sessions,sharedWork,context={}}){
  async function actor(token){const valid=await sessions.validate(token);if(!valid)throw Error('AUTHENTICATION_REQUIRED');return valid.user}
  async function workspace(user,id,permission='workspaces.view'){const item=await persistence.get(V5_STORES.workspaceInstances,id);if(!item||item.status!=='active'||!await canAccessOwnership(persistence,{userId:user.id,...item,permissionCode:permission}))throw Error('INTEGRATION_TARGET_WORKSPACE_DENIED');return item}
  async function definition(item){return persistence.get(V5_STORES.workspaceDefinitions,item.definitionId)}
  const audit=(type,user,item,metadata={})=>createEvent('audit',{eventType:type,actorUserId:user.id,organisationId:item.organisationId,unitId:item.unitId,entityType:'integration',entityId:item.id,metadata},context);
  return Object.freeze({
    async reference(token,input){const user=await actor(token),source=await sharedWork.get(token,input.sourceType,input.sourceId),target=await sharedWork.get(token,input.targetType,input.targetId);if(source.ownerType==='personal'&&target.ownerType==='organisation')throw Error('PERSONAL_REFERENCE_TO_ORGANISATION_DENIED');if(!owns(source,target)||source.workspaceId===target.workspaceId)throw Error('CROSS_WORKSPACE_REFERENCE_SCOPE_DENIED');const relationship=createRelationship({...target,sourceType:input.sourceType,sourceId:source.id,targetType:input.targetType,targetId:target.id,relationshipType:input.relationshipType||'cross_workspace_reference',createdByUserId:user.id,provenance:{origin:'reference',sourceType:input.sourceType,sourceId:source.id}},context);await persistence.runTransaction([V5_STORES.relationships,V5_STORES.auditEvents],'readwrite',async tx=>{const duplicate=(await tx.getAllByIndex(V5_STORES.relationships,'bySource',[relationship.sourceType,relationship.sourceId])).some(x=>x.targetType===relationship.targetType&&x.targetId===relationship.targetId&&x.relationshipType===relationship.relationshipType);if(duplicate)throw Error('RELATIONSHIP_DUPLICATE');await tx.add(V5_STORES.relationships,relationship);await tx.add(V5_STORES.auditEvents,audit('integration.reference_created',user,relationship,{sourceWorkspaceId:source.workspaceId,targetWorkspaceId:target.workspaceId}))});return relationship},
    async copy(token,input){const user=await actor(token);if(!SHARED_ENTITY_TYPES.includes(input.sourceType)||input.sourceType==='file')throw Error(input.sourceType==='file'?'FILE_COPY_REQUIRES_SECURE_REFERENCE':'INTEGRATION_COPY_TYPE_DENIED');const source=await sharedWork.get(token,input.sourceType,input.sourceId),target=await workspace(user,input.targetWorkspaceId);if(source.workspaceId===target.id)throw Error('INTEGRATION_COPY_TARGET_UNCHANGED');const fields=sharedFields[input.sourceType];if(!fields)throw Error('INTEGRATION_COPY_TYPE_DENIED');const copy=await sharedWork.create(token,input.sourceType,{...fields(source),ownerType:target.ownerType,ownerId:target.ownerId,organisationId:target.organisationId,unitId:target.unitId,workspaceId:target.id,provenance:{origin:'copy',sourceType:input.sourceType,sourceId:source.id,reference:source.workspaceId}});await persistence.add(V5_STORES.auditEvents,audit('integration.copy_created',user,copy,{sourceType:input.sourceType,sourceId:source.id,sourceWorkspaceId:source.workspaceId,targetWorkspaceId:target.id}));return{copy,source:{type:input.sourceType,id:source.id,workspaceId:source.workspaceId},operation:'copy'}},
    async prepareBusinessHandoff(token,input){const user=await actor(token),source=await sharedWork.get(token,input.sourceType,input.sourceId),sourceWorkspace=await workspace(user,source.workspaceId),target=await workspace(user,input.targetWorkspaceId),sourceDefinition=await definition(sourceWorkspace),targetDefinition=await definition(target);if(!['office','studio'].includes(sourceDefinition?.type)||targetDefinition?.type!=='business'||source.organisationId!==target.organisationId)throw Error('BUSINESS_HANDOFF_SCOPE_DENIED');if(sourceDefinition.type==='studio'&&input.commercial!==true)throw Error('STUDIO_HANDOFF_REQUIRES_COMMERCIAL_CONFIRMATION');const task=await sharedWork.create(token,'task',{ownerType:target.ownerType,ownerId:target.ownerId,organisationId:target.organisationId,unitId:target.unitId,workspaceId:target.id,title:input.title||`Review ${sourceDefinition.type} handoff`,description:'Explicit cross-workspace handoff ready for authorised Business review.',assigneeUserIds:[],provenance:{origin:'handoff',sourceType:input.sourceType,sourceId:source.id,reference:source.workspaceId}});await persistence.add(V5_STORES.auditEvents,audit('integration.business_handoff_prepared',user,task,{sourceWorkspaceType:sourceDefinition.type,sourceId:source.id,targetWorkspaceId:target.id}));return{task,postingCreated:false,sourceWorkspaceType:sourceDefinition.type}},
    async checkIntegrity(token,input){const user=await actor(token);if(input.ownerType==='organisation'&&!await can(persistence,{userId:user.id,organisationId:input.organisationId,unitId:input.unitId||null,permissionCode:'audit.view'}))throw Error('INTEGRITY_REVIEW_DENIED');if(input.ownerType==='personal'&&input.ownerId!==user.id)throw Error('INTEGRITY_REVIEW_DENIED');const findings=[],workspaces=(await persistence.getAll(V5_STORES.workspaceInstances)).filter(x=>owns(x,input)),units=await persistence.getAll(V5_STORES.organisationUnits),definitions=await persistence.getAll(V5_STORES.workspaceDefinitions);for(const item of workspaces){if(item.ownerType==='organisation'&&(item.ownerId!==item.organisationId||!item.organisationId))findings.push({code:'OWNERSHIP_METADATA_INVALID',entityId:item.id});if(!definitions.some(x=>x.id===item.definitionId&&x.status==='active'))findings.push({code:'WORKSPACE_DEFINITION_MISSING',entityId:item.id});if(item.unitId&&!units.some(x=>x.id===item.unitId&&x.organisationId===item.organisationId&&x.status==='active'))findings.push({code:'WORKSPACE_UNIT_INVALID',entityId:item.id})}for(const link of(await persistence.getAll(V5_STORES.relationships)).filter(x=>owns(x,input))){for(const side of ['source','target']){const type=link[`${side}Type`],id=link[`${side}Id`],store=storeByRelationshipType[type],endpoint=store&&await persistence.get(store,id);if(!endpoint)findings.push({code:'RELATIONSHIP_ENDPOINT_MISSING',entityId:link.id,side,type,id});else if(!owns(endpoint,link))findings.push({code:'RELATIONSHIP_ENDPOINT_SCOPE_INVALID',entityId:link.id,side,type,id})}}for(const receipt of(await persistence.getAll(V5_STORES.businessPostingReceipts)).filter(x=>x.organisationId===input.organisationId)){if(!await persistence.get(V5_STORES.workspaceInstances,receipt.sourceWorkspaceId)||!await persistence.get(V5_STORES.businessJournalEntries,receipt.journalEntryId))findings.push({code:'POSTING_RECEIPT_REFERENCE_INVALID',entityId:receipt.id})}return{checkedAt:new Date().toISOString(),scope:{ownerType:input.ownerType,ownerId:input.ownerId,organisationId:input.organisationId||null,unitId:input.unitId||null},valid:findings.length===0,findings,mutated:false}}
  })
}
