function registry() { const providers=new Map(); return { register(provider){if(!provider?.id||typeof provider.provide!=='function')throw Error('INVALID_PROVIDER');providers.set(provider.id,provider);return()=>providers.delete(provider.id)},async collect(input,allow){const output=[];for(const provider of providers.values())for(const item of await provider.provide(input)||[])if(await allow(item))output.push({...item,providerId:provider.id});return output} }; }
export function createExperienceServices(platform){const myDayProviders=registry(),searchProviders=registry(),quickCreateProviders=registry();const allowed=(token,context,permission='workspaces.view')=>async item=>{const inContext=context.kind==='personal'?item.ownerType==='personal'&&item.ownerId===context.ownerId:item.ownerType==='organisation'&&item.organisationId===context.organisationId&&(!context.unitId||!item.unitId||item.unitId===context.unitId);return inContext&&platform.authoriseScopedItem(token,item,permission)};return{myDay:{registerProvider:myDayProviders.register,async list(token,context){return myDayProviders.collect({token,context},allowed(token,context))}},search:{registerProvider:searchProviders.register,async search(token,context,query){const text=String(query||'').trim();return text?searchProviders.collect({token,context,query:text},allowed(token,context)):[]}},quickCreate:{registerProvider:quickCreateProviders.register,async list(token,context){return quickCreateProviders.collect({token,context},async item=>item.available!==false&&await allowed(token,context,item.permissionCode)(item))}},notifications:{list:(token,context)=>platform.listNotifications(token,context),markRead:(token,id)=>platform.markNotificationRead(token,id)}}}

const scopeOf=context=>({ownerType:context.ownerType,ownerId:context.ownerId,organisationId:context.organisationId,unitId:context.unitId,workspaceId:context.workspaceId});
export function registerSharedWorkProviders(services,platform,{clock=()=>new Date()}={}){const sharedWork=platform.sharedWork,scopes=async(token,context)=>(await platform.listAvailableWorkspaces(token,context)).map(({workspace})=>({...workspace,workspaceId:workspace.id}));
  services.myDay.registerProvider({id:'shared-work',async provide({token,context}){const now=clock(),end=new Date(now);end.setHours(23,59,59,999);let tasks=[],events=[];for(const scope of await scopes(token,context)){tasks.push(...await sharedWork.list(token,'task',scope));events.push(...await sharedWork.list(token,'event',scope))}return[...tasks.filter(x=>x.completionState!=='completed'&&x.dueAt&&new Date(x.dueAt)<=end).map(x=>({...x,kind:'task'})),...events.filter(x=>x.status==='active'&&new Date(x.startAt)<=end&&(!x.endAt||new Date(x.endAt)>=new Date(now.toDateString()))).map(x=>({...x,kind:'event'}))]}});
  services.search.registerProvider({id:'shared-work',async provide({token,context,query}){const needle=query.toLocaleLowerCase(),output=[];for(const scope of await scopes(token,context))for(const type of ['person','task','event','project','note','document','file','record'])for(const item of await sharedWork.list(token,type,scope)){const haystack=[item.title,item.displayName,item.description,item.summary,item.filename,item.reference].filter(Boolean).join(' ').toLocaleLowerCase();if(haystack.includes(needle))output.push({...item,title:item.title||item.displayName,kind:type})}return output}});
  services.quickCreate.registerProvider({id:'shared-work',async provide({token,context}){const output=[];for(const workspace of await scopes(token,context))for(const label of ['Task','Event','Note','Project','Document'])output.push({...workspace,id:`create:${workspace.id}:${label.toLowerCase()}`,label,kind:label.toLowerCase(),available:true});return output}});
}
export function registerCaptureProviders(services,platform,{capabilities={fileSelection:true,camera:false,microphone:false,pointerInk:false}}={}){const scopes=async(token,context)=>(await platform.listAvailableWorkspaces(token,context)).map(({workspace})=>({...workspace,workspaceId:workspace.id}));services.search.registerProvider({id:'knowledge',async provide({token,context,query}){const output=[],needle=query.toLocaleLowerCase();for(const itemScope of await scopes(token,context))for(const item of await platform.capture.listKnowledge(token,itemScope))if([item.title,item.sourceType,item.searchText].join(' ').toLocaleLowerCase().includes(needle))output.push({...item,kind:'knowledgeSource'});return output}});services.quickCreate.registerProvider({id:'capture',async provide({token,context}){const actions=[['Upload File','upload',capabilities.fileSelection],['Scan Document','scan',capabilities.camera||capabilities.fileSelection],['Take Photo','photo',capabilities.camera||capabilities.fileSelection],['Handwritten Note','ink',capabilities.pointerInk],['Record Audio','audio',capabilities.microphone]],output=[];for(const itemScope of await scopes(token,context))for(const[label,kind,available]of actions)if(available)output.push({...itemScope,id:`capture:${itemScope.workspaceId}:${kind}`,label,kind,available:true});return output}})}
