import {createId,ownership,timestamp} from './foundation.mjs';
export const CAPTURE_TYPES=Object.freeze(['upload','photo','scan','ink','audio','video','screen']);export const PROCESSING_STATES=Object.freeze(['pending','processing','ready','failed','unsupported']);export const KNOWLEDGE_SOURCE_TYPES=Object.freeze(['text','note','document','file','image','pdf','ink','audio','video','mediaSession']);
const text=(value,name)=>{const output=String(value||'').trim();if(!output)throw TypeError(`${name} is required.`);return output};const base=(input,context)=>{const at=input.createdAt||timestamp(context.clock);return{id:input.id||createId(context.idOptions),...ownership(input),createdByUserId:text(input.createdByUserId,'creator'),createdAt:at,updatedAt:input.updatedAt||at,status:input.status||'active',security:{classification:input.security?.classification||'internal',accessPolicy:input.security?.accessPolicy||'workspace'},provenance:{origin:input.provenance?.origin||'created',sourceType:input.provenance?.sourceType||null,sourceId:input.provenance?.sourceId||null,reference:input.provenance?.reference||null}}};const state=value=>{if(!PROCESSING_STATES.includes(value||'pending'))throw TypeError('Processing state is invalid.');return value||'pending'};
export function createCapture(input={},context={}){if(!CAPTURE_TYPES.includes(input.captureType))throw TypeError('Capture type is invalid.');return{...base(input,context),captureType:input.captureType,title:text(input.title||input.captureType,'Capture title'),fileId:input.fileId||null,inkDocumentId:input.inkDocumentId||null,mediaSessionId:input.mediaSessionId||null,processingState:state(input.processingState),sourceMetadata:{browserCapability:input.sourceMetadata?.browserCapability||null,durationMs:input.sourceMetadata?.durationMs||null}}}
export function createInkDocument(input={},context={}){const width=Number(input.width),height=Number(input.height);if(!(width>0&&height>0))throw TypeError('Ink dimensions are invalid.');const strokes=(input.strokes||[]).map(stroke=>({tool:stroke.tool||'pen',color:stroke.color||'#17211b',width:Number(stroke.width)||2,points:(stroke.points||[]).map(point=>({x:Number(point.x),y:Number(point.y),t:Number(point.t)||0,...(Number.isFinite(point.pressure)?{pressure:point.pressure}:{})}))}));if(strokes.some(stroke=>!stroke.points.length||stroke.points.some(point=>!Number.isFinite(point.x)||!Number.isFinite(point.y))))throw TypeError('Ink stroke data is invalid.');return{...base(input,context),title:text(input.title,'Ink title'),width,height,strokes,authoritativeFormat:'strokes-v1',rendering:{background:input.rendering?.background||'#ffffff'},processingState:state(input.processingState||'ready')}}
export function createMediaSession(input={},context={}){if(!['audio','video','uploaded'].includes(input.mediaType))throw TypeError('Media type is invalid.');return{...base(input,context),title:text(input.title,'Media Session title'),mediaType:input.mediaType,sessionType:input.sessionType||'recording',fileId:input.fileId||null,eventId:input.eventId||null,participantPersonIds:[...new Set(input.participantPersonIds||[])],durationMs:Number.isFinite(input.durationMs)&&input.durationMs>=0?input.durationMs:null,recordingState:input.recordingState||'completed'}}
export function createKnowledgeSource(input={},context={}){if(!KNOWLEDGE_SOURCE_TYPES.includes(input.sourceType))throw TypeError('Knowledge source type is invalid.');return{...base(input,context),title:text(input.title,'Knowledge Source title'),sourceType:input.sourceType,sourceEntityType:text(input.sourceEntityType,'Knowledge source entity type'),sourceEntityId:text(input.sourceEntityId,'Knowledge source entity ID'),processingState:state(input.processingState),searchText:String(input.searchText||'')}}
export function createDerivedArtefact(input={},context={}){return{...base(input,context),title:text(input.title,'Derived artefact title'),knowledgeSourceId:text(input.knowledgeSourceId,'Knowledge Source ID'),derivationType:text(input.derivationType,'Derivation type'),providerId:text(input.providerId,'Provider ID'),providerVersion:input.providerVersion||null,content:String(input.content||''),authoritative:false,processingState:state(input.processingState||'ready')}}
export function createProcessingJob(input={},context={}){return{...base(input,context),knowledgeSourceId:text(input.knowledgeSourceId,'Knowledge Source ID'),action:text(input.action,'Processing action'),providerId:text(input.providerId,'Provider ID'),processingState:state(input.processingState),errorCode:input.errorCode||null}}
