const UUID_V7 = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export const OWNER_TYPES = Object.freeze(['personal', 'organisation']);
export const UNIT_TYPES = Object.freeze(['subsidiary', 'agency', 'directorate', 'department', 'branch', 'regional_office', 'unit', 'team']);
export const WORKSPACE_TYPES = Object.freeze(['office', 'business', 'school', 'studio', 'space', 'custom']);

export function createId({ timestamp = Date.now(), cryptoApi = globalThis.crypto } = {}) {
  if (!cryptoApi?.getRandomValues) throw Error('A cryptographically secure random source is required.');
  const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
  let remaining = BigInt(timestamp);
  for (let index = 5; index >= 0; index -= 1) { bytes[index] = Number(remaining & 255n); remaining >>= 8n; }
  bytes[6] = (bytes[6] & 15) | 112; bytes[8] = (bytes[8] & 63) | 128;
  const hex = [...bytes].map(value => value.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}
export const isId = value => UUID_V7.test(String(value));
export const timestamp = clock => (clock || (() => new Date()))().toISOString();
const text = (value, field) => { const result = String(value || '').trim(); if (!result) throw TypeError(`${field} is required.`); return result; };
const base = (input, context) => { const at = input.createdAt || timestamp(context.clock); return { id: input.id || createId(context.idOptions), status: input.status || 'active', createdAt: at, updatedAt: input.updatedAt || at, metadata: input.metadata || {} }; };

export const createUser = (input = {}, context = {}) => ({ ...base(input, context), displayName: text(input.displayName, 'User displayName'), email: input.email ? String(input.email).trim().toLowerCase() : null });
export const createPersonalEnvironment = (input = {}, context = {}) => ({ ...base(input, context), userId: text(input.userId, 'PersonalEnvironment userId'), ownerType: 'personal', ownerId: text(input.userId, 'PersonalEnvironment ownerId') });
export const createOrganisation = (input = {}, context = {}) => ({ ...base(input, context), name: text(input.name, 'Organisation name'), organisationType: text(input.organisationType || 'other', 'Organisation type'), defaultCurrency: text(input.defaultCurrency || 'NGN', 'Organisation currency').toUpperCase(), timezone: text(input.timezone || 'Africa/Lagos', 'Organisation timezone') });
export function createOrganisationUnit(input = {}, context = {}) { if (!UNIT_TYPES.includes(input.unitType || 'unit')) throw TypeError('Organisation Unit type is invalid.'); return { ...base(input, context), organisationId: text(input.organisationId, 'OrganisationUnit organisationId'), parentUnitId: input.parentUnitId || null, name: text(input.name, 'OrganisationUnit name'), unitType: input.unitType || 'unit' }; }
export const createMembership = (input = {}, context = {}) => ({ ...base(input, context), userId: text(input.userId, 'Membership userId'), organisationId: text(input.organisationId, 'Membership organisationId') });
export const createRole = (input = {}, context = {}) => ({ ...base(input, context), organisationId: text(input.organisationId, 'Role organisationId'), code: text(input.code, 'Role code'), name: text(input.name, 'Role name'), kind: input.kind === 'custom' ? 'custom' : 'system', permissionCodes: [...new Set(input.permissionCodes || [])].sort() });
export function createRoleAssignment(input = {}, context = {}) { const scopeType = input.scopeType || 'organisation'; if (!['organisation', 'units'].includes(scopeType)) throw TypeError('RoleAssignment scopeType is invalid.'); const unitIds = [...new Set(input.unitIds || [])]; if (scopeType === 'organisation' && unitIds.length) throw TypeError('Organisation-scoped assignment cannot include units.'); if (scopeType === 'units' && !unitIds.length) throw TypeError('Unit-scoped assignment requires units.'); return { ...base(input, context), membershipId: text(input.membershipId, 'RoleAssignment membershipId'), organisationId: text(input.organisationId, 'RoleAssignment organisationId'), roleId: text(input.roleId, 'RoleAssignment roleId'), scopeType, unitIds }; }
export function createWorkspaceDefinition(input = {}, context = {}) { if (!WORKSPACE_TYPES.includes(input.type)) throw TypeError('Workspace type is invalid.'); return { ...base(input, context), type: input.type, code: text(input.code, 'WorkspaceDefinition code'), name: text(input.name, 'WorkspaceDefinition name'), standard: input.type !== 'custom', registeredByUserId: input.registeredByUserId || null, organisationId: input.organisationId || null }; }
export function ownership(input = {}) { if (!OWNER_TYPES.includes(input.ownerType)) throw TypeError('Owner type is required and must be personal or organisation.'); const ownerId = text(input.ownerId, 'ownerId'), organisationId = input.ownerType === 'organisation' ? text(input.organisationId || ownerId, 'organisationId') : null; if (input.ownerType === 'personal' && input.organisationId) throw TypeError('Personal records cannot carry organisation ownership.'); return { ownerType: input.ownerType, ownerId, organisationId, unitId: input.unitId || null, workspaceId: input.workspaceId || null }; }
export const createWorkspaceInstance = (input = {}, context = {}) => ({ ...base(input, context), ...ownership(input), definitionId: text(input.definitionId, 'Workspace definitionId'), name: text(input.name, 'Workspace name'), createdByUserId: text(input.createdByUserId, 'Workspace creator') });
export const createScopedRecord = (input = {}, context = {}) => ({ ...base(input, context), ...ownership(input), createdByUserId: text(input.createdByUserId, 'Record creator'), security: { classification: input.security?.classification || 'internal', accessPolicy: input.security?.accessPolicy || 'workspace' } });
export const createEvent = (kind, input = {}, context = {}) => ({ id: input.id || createId(context.idOptions), kind, eventType: text(input.eventType, 'Event type'), actorUserId: input.actorUserId || null, organisationId: input.organisationId || null, unitId: input.unitId || null, entityType: text(input.entityType, 'Event entityType'), entityId: text(input.entityId, 'Event entityId'), occurredAt: input.occurredAt || timestamp(context.clock), metadata: input.metadata || {} });
