import { createId, ownership, timestamp } from './foundation.mjs';
export const SHARED_ENTITY_TYPES=Object.freeze(['person','task','event','project','note','document','file','record']);
export const STORE_BY_TYPE=Object.freeze({person:'people',task:'tasks',event:'events',project:'projects',note:'notes',document:'documents',file:'files',record:'records'});
const required=(value,name)=>{const text=String(value||'').trim();if(!text)throw TypeError(`${name} is required.`);return text};
const iso=(value,name,optional=true)=>{if(value==null&&optional)return null;const date=new Date(value);if(Number.isNaN(date.valueOf()))throw TypeError(`${name} is invalid.`);return date.toISOString()};
const unique=value=>[...new Set(value||[])];
const provenance=input=>({origin:input?.origin||'created',sourceType:input?.sourceType||null,sourceId:input?.sourceId||null,reference:input?.reference||null});
const base=(input,context)=>{const at=input.createdAt||timestamp(context.clock);return{id:input.id||createId(context.idOptions),...ownership(input),createdByUserId:required(input.createdByUserId,'creator'),createdAt:at,updatedAt:input.updatedAt||at,status:input.status||'active',security:{classification:input.security?.classification||'internal',accessPolicy:input.security?.accessPolicy||'workspace'},provenance:provenance(input.provenance)}};
export function createSharedEntity(type,input={},context={}){if(!SHARED_ENTITY_TYPES.includes(type))throw TypeError('Shared entity type is invalid.');const common=base(input,context),title=()=>required(input.title,`${type} title`);if(type==='person')return{...common,displayName:required(input.displayName,'Person displayName'),contextualRoles:unique(input.contextualRoles),email:input.email?String(input.email).trim().toLowerCase():null,phone:input.phone?String(input.phone).trim():null};if(type==='task')return{...common,title:title(),description:String(input.description||''),priority:input.priority||'normal',assigneeUserIds:unique(input.assigneeUserIds),dueAt:iso(input.dueAt,'Task dueAt'),completedAt:iso(input.completedAt,'Task completedAt'),completionState:input.completionState||'open'};if(type==='event'){const startAt=iso(input.startAt,'Event startAt',false),endAt=iso(input.endAt,'Event endAt');if(endAt&&endAt<startAt)throw TypeError('Event endAt precedes startAt.');return{...common,title:title(),description:String(input.description||''),startAt,endAt,allDay:Boolean(input.allDay),location:String(input.location||''),participantPersonIds:unique(input.participantPersonIds)}}if(type==='project')return{...common,title:title(),description:String(input.description||''),startDate:iso(input.startDate,'Project startDate'),targetDate:iso(input.targetDate,'Project targetDate'),responsibleUserIds:unique(input.responsibleUserIds)};if(type==='note')return{...common,title:title(),content:String(input.content||'')};if(type==='document')return{...common,title:title(),summary:String(input.summary||''),documentType:input.documentType||'general',version:input.version||1};if(type==='file')return{...common,title:required(input.displayName||input.filename,'File displayName'),filename:required(input.filename,'File filename'),mediaType:required(input.mediaType,'File mediaType'),size:Number.isSafeInteger(input.size)&&input.size>=0?input.size:(()=>{throw TypeError('File size is invalid.')})(),storageProvider:input.storageProvider||'indexeddb',storageKey:input.storageKey||null,source:input.source||'upload'};return{...common,title:title(),recordType:required(input.recordType,'Record type'),reference:input.reference||null,recordedAt:iso(input.recordedAt||common.createdAt,'Record recordedAt',false),retention:{classification:input.retention?.classification||'standard',reviewAt:iso(input.retention?.reviewAt,'Retention reviewAt'),disposition:input.retention?.disposition||'review'}}}
export function createRelationship(input={},context={}){if(!SHARED_ENTITY_TYPES.includes(input.sourceType)||!SHARED_ENTITY_TYPES.includes(input.targetType))throw TypeError('Relationship entity type is invalid.');if(input.sourceType===input.targetType&&input.sourceId===input.targetId)throw TypeError('Self relationship is invalid.');const at=input.createdAt||timestamp(context.clock);return{id:input.id||createId(context.idOptions),...ownership(input),sourceType:input.sourceType,sourceId:required(input.sourceId,'Relationship sourceId'),targetType:input.targetType,targetId:required(input.targetId,'Relationship targetId'),relationshipType:required(input.relationshipType,'Relationship type'),createdByUserId:required(input.createdByUserId,'Relationship creator'),createdAt:at,provenance:provenance(input.provenance)}}
