import{createV4Application}from'../application/application.mjs';
import{V4_STORES}from'../persistence/schema.mjs';
import{createMigrationService}from'./migration.mjs';
import{REHEARSAL_DATABASE_NAME,deleteRehearsalDatabase,parseRehearsalSnapshot}from'./rehearsal-import.mjs';

const $=selector=>document.querySelector(selector),escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),show=(target,value)=>{$(target).innerHTML=`<pre>${escape(JSON.stringify(value,null,2))}</pre>`},message=(text,error=false)=>{$('#message').className=error?'error':'success';$('#message').textContent=text},iso=value=>{if(!value)throw new Error('Verification timestamp is required.');return new Date(value).toISOString()},integer=(value,label)=>{if(value===''||!Number.isSafeInteger(Number(value)))throw new Error(`${label} must be an integer number of minor units.`);return Number(value)};
let app,migration,snapshot,run,reconciliation,accounts=[];

function enable(id,value=true){$(id).disabled=!value}
function evidence(prefix,actor){const status=$(`#${prefix}-status`).value,amount=$(`#${prefix}-amount`).value,reference=$(`#${prefix}-reference`).value.trim();if(status==='verified')return{status,amountMinor:integer(amount,`Opening ${prefix.toUpperCase()}`),verifiedAt:iso($(`#${prefix}-at`).value),verificationReference:reference};if(status==='not_applicable')return{status,amountMinor:0,reason:reference};return{status,reason:reference,verifier:actor}}
function renderIssues(value){return{status:value.run?.status??run?.status,warnings:value.warnings??value.run?.warnings??[],blockers:value.blockers??value.run?.blockers??[],results:value.results??[]}}
function renderWarningAcceptance(){const warnings=[...new Set((reconciliation?.warnings||[]).map(item=>item.code))];$('#warning-acceptance').innerHTML=warnings.length?`<p>Explicitly accept every warning:</p>${warnings.map(code=>`<label><input type="checkbox" class="accepted-warning" value="${escape(code)}"> ${escape(code)}</label>`).join('')}`:'<p>No warnings require acceptance.</p>'}

async function guarded(work){try{message('Working…');await work()}catch(error){message(error.message||String(error),true)}}

$('#import').onclick=()=>guarded(async()=>{const file=$('#snapshot-file').files[0];if(!file)throw new Error('Select a captured snapshot JSON file.');const envelope=parseRehearsalSnapshot(await file.text());app=await createV4Application({indexedDB,databaseName:REHEARSAL_DATABASE_NAME,bootstrap:{businessName:'Phase 8 Isolated Rehearsal'}});const existing=await app.persistence.getAll(V4_STORES.migrationRuns);if(existing.length){app.close();app=null;throw new Error('The dedicated rehearsal database already contains a run. Review it separately or reset before importing a new snapshot.')}migration=createMigrationService(app.persistence);snapshot=await migration.createSnapshot(envelope);const verification=await migration.verifySnapshot(snapshot);$('#snapshot-result').innerHTML=`<dl><dt>Created by</dt><dd>${escape(snapshot.createdBy)}</dd><dt>Build reference</dt><dd>${escape(snapshot.buildReference)}</dd><dt>Created at</dt><dd>${escape(snapshot.createdAt)}</dd><dt>Verification</dt><dd class="success">${verification.valid?'Verified':'Failed'}</dd><dt>Aggregate checksum</dt><dd><code>${escape(snapshot.aggregateChecksum)}</code></dd></dl><table><thead><tr><th>V3 key</th><th>SHA-256</th></tr></thead><tbody>${Object.entries(snapshot.keyChecksums).map(([key,sum])=>`<tr><td>${escape(key)}</td><td><code>${escape(sum)}</code></td></tr>`).join('')}</tbody></table>`;enable('#analyze');message('Snapshot imported into the isolated rehearsal database and verified.')});

$('#analyze').onclick=()=>guarded(async()=>{const actor=$('#operator').value.trim();if(!actor)throw new Error('Operator identity is required.');const cutoverAt=iso($('#cutover-at').value),ctx=app.getContext();run=await migration.createRun({snapshotId:snapshot.id,businessId:ctx.businessId,operatingUnitId:ctx.operatingUnitId,inventoryLocationId:ctx.inventoryLocationId,baseCurrency:ctx.baseCurrency,cutoverAt,actorId:actor});show('#run-result',renderIssues({run}));enable('#execute',run.status==='ready'&&!run.blockers?.length);message(run.status==='ready'?'Analysis complete. Target is isolated and ready.':'Analysis found blockers.',run.status!=='ready')});

$('#execute').onclick=()=>guarded(async()=>{run=await migration.execute(run.id);show('#run-result',renderIssues({run}));enable('#execute',false);enable('#reconcile',run.status==='migrated');message('Migration executed in the dedicated rehearsal database.')});

$('#reconcile').onclick=()=>guarded(async()=>{reconciliation=await migration.reconcile(run.id);run=reconciliation.run;show('#reconciliation-result',renderIssues(reconciliation));renderWarningAcceptance();enable('#reconcile',false);enable('#opening',reconciliation.readyForAcceptance);accounts=await app.persistence.getAll(V4_STORES.ledgerAccounts);const financial=(await app.persistence.getAll(V4_STORES.financialAccounts)).filter(item=>item.businessId===run.businessId&&item.status==='active'),required=[{label:'Cash',accountId:accounts.find(item=>item.businessId===run.businessId&&item.systemRole==='cash_on_hand')?.id},...financial.filter(item=>item.type==='bank_account').map(item=>({label:`Bank: ${item.displayName}`,accountId:item.ledgerAccountId}))],inventory=accounts.find(item=>item.businessId===run.businessId&&item.systemRole==='inventory_asset');$('#balance-fields').innerHTML=`${required.map((item,index)=>`<fieldset class="balance" data-account="${escape(item.accountId)}"><legend>${escape(item.label)}</legend><label>Amount <input class="amount" type="number" step="1"></label><label>Verified at <input class="verified-at" type="datetime-local"></label><label>Reference/evidence <input class="reference"></label></fieldset>`).join('')}<fieldset class="balance optional" data-account="${escape(inventory?.id)}"><legend>Known inventory valuation (optional; leave blank when unknown)</legend><label>Amount <input class="amount" type="number" step="1"></label><label>Verified at <input class="verified-at" type="datetime-local"></label><label>Reference/evidence <input class="reference"></label></fieldset>`;message(reconciliation.readyForAcceptance?'Reconciliation completed. Enter opening evidence.':'Reconciliation has blockers.',!reconciliation.readyForAcceptance)});

$('#opening').onclick=()=>guarded(async()=>{const actor=$('#operator').value.trim(),balances=[];for(const field of document.querySelectorAll('.balance')){const amount=field.querySelector('.amount').value;if(field.classList.contains('optional')&&amount==='')continue;balances.push({accountId:field.dataset.account,amountMinor:integer(amount,field.querySelector('legend').textContent),verifiedAt:iso(field.querySelector('.verified-at').value),verificationReference:field.querySelector('.reference').value.trim()})}const ar=evidence('ar',actor),ap=evidence('ap',actor),byRole=Object.fromEntries(accounts.filter(item=>item.businessId===run.businessId&&item.systemRole).map(item=>[item.systemRole,item]));if(ar.status==='verified')balances.push({accountId:byRole.accounts_receivable.id,amountMinor:ar.amountMinor,verifiedAt:ar.verifiedAt,verificationReference:ar.verificationReference});if(ap.status==='verified')balances.push({accountId:byRole.accounts_payable.id,amountMinor:-ap.amountMinor,verifiedAt:ap.verifiedAt,verificationReference:ap.verificationReference});await migration.recordOpeningPosition(run.id,{actor,receivables:ar,payables:ap,balances},app.services.finance);enable('#opening',false);enable('#readiness');message('Opening position recorded through the Phase 8 finance service.')});

$('#readiness').onclick=()=>guarded(async()=>{const ready=await migration.readiness(run.id);show('#readiness-result',ready);enable('#accept',ready.blockers.length===0);message(ready.blockers.length?'Readiness has blockers.':'Readiness checks passed; warning acceptance is still required.',ready.blockers.length>0)});

$('#accept').onclick=()=>guarded(async()=>{const actor=$('#operator').value.trim(),required=[...new Set((reconciliation?.warnings||[]).map(item=>item.code))],accepted=[...document.querySelectorAll('.accepted-warning:checked')].map(item=>item.value);if(required.some(code=>!accepted.includes(code)))throw new Error('Every service-generated warning must be explicitly accepted.');run=await migration.accept(run.id,{actor,acceptedWarnings:accepted});$('#accept-result').innerHTML=`<h3 class="success">REHEARSAL ACCEPTED</h3><p>Run <code>${escape(run.id)}</code> — status <strong>${escape(run.status)}</strong></p><p>Stop here. This interface provides no production cutover actions.</p>`;enable('#accept',false);message('Rehearsal accepted. Stop before production operations.')});

$('#reset').onclick=()=>guarded(async()=>{if(!confirm(`Delete only ${REHEARSAL_DATABASE_NAME}? This cannot be undone.`))return;app?.close();app=null;await deleteRehearsalDatabase();location.reload()});
